// io_catalog_extra.js — GENERAT de tools/gen-io-catalog-extra.js din specul oficial FMC130.
// NU edita de mână. Catalogul scris de mână (io_catalog.js) are prioritate; aici e restul listei
// oficiale (400 intrări), ca editorul „Mapează" și DevConsole să aibă etichete pentru tot.
module.exports = [
  { id: 502, name: "MSP500 speed sensor", name_ro: "MSP500 viteză senzor", unit: "-", multiplier: 1, category: "Sistem", key: "msp500_speed_sensor", desc_ro: "" },
  { id: 10800, name: "EYE Temperature 1", name_ro: "EYE temperatură 1", unit: "°C", multiplier: 0.01, category: "Sistem", key: "eye_temperature_1", desc_ro: "" },
  { id: 10801, name: "EYE Temperature 2", name_ro: "EYE temperatură 2", unit: "°C", multiplier: 0.01, category: "Sistem", key: "eye_temperature_2", desc_ro: "" },
  { id: 10802, name: "EYE Temperature 3", name_ro: "EYE temperatură 3", unit: "°C", multiplier: 0.01, category: "Sistem", key: "eye_temperature_3", desc_ro: "" },
  { id: 10803, name: "EYE Temperature 4", name_ro: "EYE temperatură 4", unit: "°C", multiplier: 0.01, category: "Sistem", key: "eye_temperature_4", desc_ro: "" },
  { id: 10804, name: "EYE Humidity 1", name_ro: "EYE umiditate 1", unit: "%", multiplier: 1, category: "Sistem", key: "eye_humidity_1", desc_ro: "" },
  { id: 10805, name: "EYE Humidity 2", name_ro: "EYE umiditate 2", unit: "%", multiplier: 1, category: "Sistem", key: "eye_humidity_2", desc_ro: "" },
  { id: 10806, name: "EYE Humidity 3", name_ro: "EYE umiditate 3", unit: "%", multiplier: 1, category: "Sistem", key: "eye_humidity_3", desc_ro: "" },
  { id: 10807, name: "EYE Humidity 4", name_ro: "EYE umiditate 4", unit: "%", multiplier: 1, category: "Sistem", key: "eye_humidity_4", desc_ro: "" },
  { id: 10808, name: "EYE Magnet 1", name_ro: "EYE magnet 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_1", desc_ro: "" },
  { id: 10809, name: "EYE Magnet 2", name_ro: "EYE magnet 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_2", desc_ro: "" },
  { id: 10810, name: "EYE Magnet 3", name_ro: "EYE magnet 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_3", desc_ro: "" },
  { id: 10811, name: "EYE Magnet 4", name_ro: "EYE magnet 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_4", desc_ro: "" },
  { id: 10812, name: "EYE Movement 1", name_ro: "EYE mișcare 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_1", desc_ro: "" },
  { id: 10813, name: "EYE Movement 2", name_ro: "EYE mișcare 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_2", desc_ro: "" },
  { id: 10814, name: "EYE Movement 3", name_ro: "EYE mișcare 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_3", desc_ro: "" },
  { id: 10815, name: "EYE Movement 4", name_ro: "EYE mișcare 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_4", desc_ro: "" },
  { id: 10816, name: "EYE Pitch 1", name_ro: "EYE înclinare 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_pitch_1", desc_ro: "" },
  { id: 10817, name: "EYE Pitch 2", name_ro: "EYE înclinare 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_pitch_2", desc_ro: "" },
  { id: 10818, name: "EYE Pitch 3", name_ro: "EYE înclinare 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_pitch_3", desc_ro: "" },
  { id: 10819, name: "EYE Pitch 4", name_ro: "EYE înclinare 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_pitch_4", desc_ro: "" },
  { id: 10820, name: "EYE Low Battery 1", name_ro: "EYE Low baterie 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_low_battery_1", desc_ro: "" },
  { id: 10821, name: "EYE Low Battery 2", name_ro: "EYE Low baterie 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_low_battery_2", desc_ro: "" },
  { id: 10822, name: "EYE Low Battery 3", name_ro: "EYE Low baterie 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_low_battery_3", desc_ro: "" },
  { id: 10823, name: "EYE Low Battery 4", name_ro: "EYE Low baterie 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_low_battery_4", desc_ro: "" },
  { id: 10824, name: "EYE Battery Voltage 1", name_ro: "EYE baterie tensiune 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_battery_voltage_1", desc_ro: "" },
  { id: 10825, name: "EYE Battery Voltage 2", name_ro: "EYE baterie tensiune 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_battery_voltage_2", desc_ro: "" },
  { id: 10826, name: "EYE Battery Voltage 3", name_ro: "EYE baterie tensiune 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_battery_voltage_3", desc_ro: "" },
  { id: 10827, name: "EYE Battery Voltage 4", name_ro: "EYE baterie tensiune 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_battery_voltage_4", desc_ro: "" },
  { id: 10832, name: "EYE Roll 1", name_ro: "EYE ruliu 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_roll_1", desc_ro: "" },
  { id: 10833, name: "EYE Roll 2", name_ro: "EYE ruliu 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_roll_2", desc_ro: "" },
  { id: 10834, name: "EYE Roll 3", name_ro: "EYE ruliu 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_roll_3", desc_ro: "" },
  { id: 10835, name: "EYE Roll 4", name_ro: "EYE ruliu 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_roll_4", desc_ro: "" },
  { id: 10836, name: "EYE Movement count 1", name_ro: "EYE mișcare număr 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_count_1", desc_ro: "" },
  { id: 10837, name: "EYE Movement count 2", name_ro: "EYE mișcare număr 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_count_2", desc_ro: "" },
  { id: 10838, name: "EYE Movement count 3", name_ro: "EYE mișcare număr 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_count_3", desc_ro: "" },
  { id: 10839, name: "EYE Movement count 4", name_ro: "EYE mișcare număr 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_movement_count_4", desc_ro: "" },
  { id: 10840, name: "EYE Magnet count 1", name_ro: "EYE magnet număr 1", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_count_1", desc_ro: "" },
  { id: 10841, name: "EYE Magnet count 2", name_ro: "EYE magnet număr 2", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_count_2", desc_ro: "" },
  { id: 10842, name: "EYE Magnet count 3", name_ro: "EYE magnet număr 3", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_count_3", desc_ro: "" },
  { id: 10843, name: "EYE Magnet count 4", name_ro: "EYE magnet număr 4", unit: "-", multiplier: 1, category: "Sistem", key: "eye_magnet_count_4", desc_ro: "" },
  { id: 383, name: "AXL Calibration Status", name_ro: "AXL Calibration stare", unit: "-", multiplier: 1, category: "Sistem", key: "axl_calibration_status", desc_ro: "" },
  { id: 451, name: "BLE RFID #1", name_ro: "BLE RFID #1", unit: "-", multiplier: 1, category: "Sistem", key: "ble_rfid_1", desc_ro: "" },
  { id: 452, name: "BLE RFID #2", name_ro: "BLE RFID #2", unit: "-", multiplier: 1, category: "Sistem", key: "ble_rfid_2", desc_ro: "" },
  { id: 453, name: "BLE RFID #3", name_ro: "BLE RFID #3", unit: "-", multiplier: 1, category: "Sistem", key: "ble_rfid_3", desc_ro: "" },
  { id: 454, name: "BLE RFID #4", name_ro: "BLE RFID #4", unit: "-", multiplier: 1, category: "Sistem", key: "ble_rfid_4", desc_ro: "" },
  { id: 455, name: "BLE Button 1 state #1", name_ro: "BLE buton 1 stare #1", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_1_state_1", desc_ro: "" },
  { id: 456, name: "BLE Button 1 state #2", name_ro: "BLE buton 1 stare #2", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_1_state_2", desc_ro: "" },
  { id: 457, name: "BLE Button 1 state #3", name_ro: "BLE buton 1 stare #3", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_1_state_3", desc_ro: "" },
  { id: 458, name: "BLE Button 1 state #4", name_ro: "BLE buton 1 stare #4", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_1_state_4", desc_ro: "" },
  { id: 459, name: "BLE Button 2 state #1", name_ro: "BLE buton 2 stare #1", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_2_state_1", desc_ro: "" },
  { id: 460, name: "BLE Button 2 state #2", name_ro: "BLE buton 2 stare #2", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_2_state_2", desc_ro: "" },
  { id: 461, name: "BLE Button 2 state #3", name_ro: "BLE buton 2 stare #3", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_2_state_3", desc_ro: "" },
  { id: 462, name: "BLE Button 2 state #4", name_ro: "BLE buton 2 stare #4", unit: "-", multiplier: 1, category: "Sistem", key: "ble_button_2_state_4", desc_ro: "" },
  { id: 622, name: "Frequency DIN1", name_ro: "Frecvență DIN1", unit: "Hz", multiplier: 0.1, category: "Sistem", key: "frequency_din1", desc_ro: "" },
  { id: 623, name: "Frequency DIN2", name_ro: "Frecvență DIN2", unit: "Hz", multiplier: 0.1, category: "Sistem", key: "frequency_din2", desc_ro: "" },
  { id: 1148, name: "Connectivity quality", name_ro: "Connectivity quality", unit: "-", multiplier: 1, category: "Sistem", key: "connectivity_quality", desc_ro: "" },
  { id: 1149, name: "Current LTE Band", name_ro: "Curent LTE Band", unit: "-", multiplier: 1, category: "Sistem", key: "current_lte_band", desc_ro: "" },
  { id: 13201, name: "PCB Temperature", name_ro: "PCB temperatură", unit: "°C", multiplier: 0.1, category: "Sistem", key: "pcb_temperature", desc_ro: "" },
  { id: 153, name: "Geofence zone 22", name_ro: "Geofence zone 22", unit: "-", multiplier: 1, category: "Sistem", key: "geofence_zone_22", desc_ro: "" },
  { id: 154, name: "Geofence zone 23", name_ro: "Geofence zone 23", unit: "-", multiplier: 1, category: "Sistem", key: "geofence_zone_23", desc_ro: "" },
  { id: 209, name: "Geofence zone 34", name_ro: "Geofence zone 34", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 216, name: "Geofence zone 35", name_ro: "Geofence zone 35", unit: "-", multiplier: 1, category: "Sistem", key: "geofence_zone_35", desc_ro: "" },
  { id: 217, name: "Geofence zone 36", name_ro: "Geofence zone 36", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 218, name: "Geofence zone 37", name_ro: "Geofence zone 37", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 221, name: "Geofence zone 40", name_ro: "Geofence zone 40", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 224, name: "Geofence zone 43", name_ro: "Geofence zone 43", unit: "-", multiplier: 1, category: "Sistem", key: "geofence_zone_43", desc_ro: "" },
  { id: 225, name: "Geofence zone 44", name_ro: "Geofence zone 44", unit: "-", multiplier: 1, category: "Sistem", key: "geofence_zone_44", desc_ro: "" },
  { id: 230, name: "Geofence zone 49", name_ro: "Geofence zone 49", unit: "-", multiplier: 1, category: "Sistem", key: "geofence_zone_49", desc_ro: "" },
  { id: 285, name: "Blood alcohol content", name_ro: "Blood alcohol content", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 283, name: "Driving State", name_ro: "Condus stare", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 284, name: "Driving Records", name_ro: "Condus Records", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 317, name: "Crash event counter", name_ro: "Crash event contor", unit: "-", multiplier: 1, category: "Sistem", key: "crash_event_counter", desc_ro: "" },
  { id: 318, name: "GNSS Jamming", name_ro: "GNSS Jamming", unit: "-", multiplier: 1, category: "Sistem", key: "gnss_jamming", desc_ro: "" },
  { id: 449, name: "Ignition On Counter", name_ro: "Ignition On contor", unit: "s", multiplier: 1, category: "Sistem", key: "ignition_on_counter", desc_ro: "" },
  { id: 1412, name: "Motorcycle Fall Detection", name_ro: "Motorcycle Fall Detection", unit: "-", multiplier: 1, category: "Sistem", key: "motorcycle_fall_detection", desc_ro: "" },
  { id: 48, name: "Fuel Level", name_ro: "Nivel combustibil", unit: "%", multiplier: 1, category: "OBD", key: "obd_fuel_level", desc_ro: "" },
  { id: 49, name: "Distance Since Codes Clear", name_ro: "Distanță de la ștergerea erorilor", unit: "km", multiplier: 1, category: "OBD", key: "obd_distance_since_codes_clear", desc_ro: "" },
  { id: 759, name: "Fuel Type", name_ro: "Combustibil Type", unit: "-", multiplier: 1, category: "OBD", key: "obd_fuel_type", desc_ro: "" },
  { id: 53, name: "Ambient Air Temperature", name_ro: "Temperatură aer ambiant", unit: "°C", multiplier: 1, category: "OBD", key: "obd_ambient_air_temperature", desc_ro: "" },
  { id: 54, name: "Time Run With MIL On", name_ro: "Timp cu martorul MIL aprins", unit: "min", multiplier: 1, category: "OBD", key: "obd_time_run_with_mil_on", desc_ro: "" },
  { id: 55, name: "Time Since Codes Cleared", name_ro: "Timp de la ștergerea erorilor", unit: "min", multiplier: 1, category: "OBD", key: "obd_time_since_codes_cleared", desc_ro: "" },
  { id: 56, name: "Absolute Fuel Rail Pressure", name_ro: "Presiune absolută rampă combustibil", unit: "kPa", multiplier: 10, category: "OBD", key: "obd_absolute_fuel_rail_pressure", desc_ro: "" },
  { id: 57, name: "Hybrid battery pack life", name_ro: "Hybrid baterie pack life", unit: "%", multiplier: 1, category: "OBD", key: "obd_hybrid_battery_pack_life", desc_ro: "" },
  { id: 58, name: "Engine Oil Temperature", name_ro: "Temperatură ulei motor", unit: "°C", multiplier: 1, category: "OBD", key: "obd_engine_oil_temperature", desc_ro: "" },
  { id: 59, name: "Fuel injection timing", name_ro: "Avans injecție", unit: "°", multiplier: 0.01, category: "OBD", key: "obd_fuel_injection_timing", desc_ro: "" },
  { id: 540, name: "Throttle position group", name_ro: "Throttle poziție group", unit: "%", multiplier: 1, category: "OBD", key: "obd_throttle_position_group", desc_ro: "" },
  { id: 541, name: "Commanded Equivalence R", name_ro: "Commanded Equivalence R", unit: "-", multiplier: 0.01, category: "OBD", key: "obd_commanded_equivalence_r", desc_ro: "" },
  { id: 542, name: "Intake MAP 2 bytes", name_ro: "Intake MAP 2 bytes", unit: "kPa", multiplier: 1, category: "OBD", key: "obd_intake_map_2_bytes", desc_ro: "" },
  { id: 543, name: "Hybrid System Voltage", name_ro: "Hybrid System tensiune", unit: "V", multiplier: 1, category: "OBD", key: "obd_hybrid_system_voltage", desc_ro: "" },
  { id: 544, name: "Hybrid System Current", name_ro: "Hybrid System curent", unit: "A", multiplier: 1, category: "OBD", key: "obd_hybrid_system_current", desc_ro: "" },
  { id: 281, name: "Fault Codes", name_ro: "Fault Codes", unit: "-", multiplier: 1, category: "OBD", key: "obd_fault_codes", desc_ro: "" },
  { id: 1593, name: "Calc Remaining Distance", name_ro: "Calc rămas distanță", unit: "Km", multiplier: 1, category: "OBD", key: "obd_calc_remaining_distance", desc_ro: "" },
  { id: 402, name: "OEM Distance Until Service", name_ro: "OEM distanță Until Service", unit: "km", multiplier: 1, category: "OBD", key: "obd_oem_oem_distance_until_service", desc_ro: "" },
  { id: 411, name: "OEM Battery charge level", name_ro: "OEM baterie charge nivel", unit: "%", multiplier: 1, category: "OBD", key: "obd_oem_oem_battery_charge_level", desc_ro: "" },
  { id: 755, name: "OEM Remaining distance", name_ro: "OEM rămas distanță", unit: "km", multiplier: 1, category: "OBD", key: "obd_oem_oem_remaining_distance", desc_ro: "" },
  { id: 1151, name: "OEM Battery State Of Health", name_ro: "OEM baterie stare Of Health", unit: "%", multiplier: 1, category: "OBD", key: "obd_oem_oem_battery_state_of_health", desc_ro: "" },
  { id: 1152, name: "OEM Battery Temperature", name_ro: "OEM baterie temperatură", unit: "°C", multiplier: 1, category: "OBD", key: "obd_oem_oem_battery_temperature", desc_ro: "" },
  { id: 385, name: "Beacon", name_ro: "Beacon", unit: "-", multiplier: 1, category: "Sistem", key: "beacon", desc_ro: "" },
  { id: 548, name: "Advanced BLE Beacon data", name_ro: "Advanced BLE Beacon data", unit: "-", multiplier: 1, category: "Sistem", key: "advanced_ble_beacon_data", desc_ro: "" },
  { id: 106, name: "BLE Humidity #3", name_ro: "BLE umiditate #3", unit: "%RH", multiplier: 0.1, category: "BLE", key: "ble_humidity_3", desc_ro: "" },
  { id: 270, name: "BLE Fuel Level #1", name_ro: "BLE combustibil nivel #1", unit: "-", multiplier: 1, category: "BLE", key: null, desc_ro: "" },
  { id: 273, name: "BLE Fuel Level #2", name_ro: "BLE combustibil nivel #2", unit: "-", multiplier: 1, category: "BLE", key: null, desc_ro: "" },
  { id: 276, name: "BLE Fuel Level #3", name_ro: "BLE combustibil nivel #3", unit: "-", multiplier: 1, category: "BLE", key: null, desc_ro: "" },
  { id: 279, name: "BLE Fuel Level #4", name_ro: "BLE combustibil nivel #4", unit: "-", multiplier: 1, category: "BLE", key: null, desc_ro: "" },
  { id: 306, name: "BLE Fuel Frequency #1", name_ro: "BLE combustibil frecvență #1", unit: "-", multiplier: 1, category: "BLE", key: "ble_fuel_frequency_1_306", desc_ro: "" },
  { id: 307, name: "BLE Fuel Frequency #2", name_ro: "BLE combustibil frecvență #2", unit: "-", multiplier: 1, category: "BLE", key: "ble_fuel_frequency_2_307", desc_ro: "" },
  { id: 308, name: "BLE Fuel Frequency #3", name_ro: "BLE combustibil frecvență #3", unit: "-", multiplier: 1, category: "BLE", key: "ble_fuel_frequency_3_308", desc_ro: "" },
  { id: 309, name: "BLE Fuel Frequency #4", name_ro: "BLE combustibil frecvență #4", unit: "-", multiplier: 1, category: "BLE", key: "ble_fuel_frequency_4_309", desc_ro: "" },
  { id: 335, name: "BLE Luminosity #1", name_ro: "BLE luminozitate #1", unit: "lx", multiplier: 1, category: "BLE", key: "ble_luminosity_1", desc_ro: "" },
  { id: 336, name: "BLE Luminosity #2", name_ro: "BLE luminozitate #2", unit: "lx", multiplier: 1, category: "BLE", key: "ble_luminosity_2", desc_ro: "" },
  { id: 337, name: "BLE Luminosity #3", name_ro: "BLE luminozitate #3", unit: "lx", multiplier: 1, category: "BLE", key: "ble_luminosity_3", desc_ro: "" },
  { id: 338, name: "BLE Luminosity #4", name_ro: "BLE luminozitate #4", unit: "lx", multiplier: 1, category: "BLE", key: "ble_luminosity_4", desc_ro: "" },
  { id: 331, name: "BLE 1 Custom #1", name_ro: "BLE 1 Custom #1", unit: "-", multiplier: 1, category: "BLE", key: "ble_1_custom_1", desc_ro: "" },
  { id: 463, name: "BLE 1 Custom #2", name_ro: "BLE 1 Custom #2", unit: "-", multiplier: 1, category: "BLE", key: "ble_1_custom_2", desc_ro: "" },
  { id: 464, name: "BLE 1 Custom #3", name_ro: "BLE 1 Custom #3", unit: "-", multiplier: 1, category: "BLE", key: "ble_1_custom_3", desc_ro: "" },
  { id: 465, name: "BLE 1 Custom #4", name_ro: "BLE 1 Custom #4", unit: "-", multiplier: 1, category: "BLE", key: "ble_1_custom_4", desc_ro: "" },
  { id: 466, name: "BLE 1 Custom #5", name_ro: "BLE 1 Custom #5", unit: "-", multiplier: 1, category: "BLE", key: "ble_1_custom_5", desc_ro: "" },
  { id: 332, name: "BLE 2 Custom #1", name_ro: "BLE 2 Custom #1", unit: "-", multiplier: 1, category: "BLE", key: "ble_2_custom_1", desc_ro: "" },
  { id: 467, name: "BLE 2 Custom #2", name_ro: "BLE 2 Custom #2", unit: "-", multiplier: 1, category: "BLE", key: "ble_2_custom_2", desc_ro: "" },
  { id: 468, name: "BLE 2 Custom #3", name_ro: "BLE 2 Custom #3", unit: "-", multiplier: 1, category: "BLE", key: "ble_2_custom_3", desc_ro: "" },
  { id: 469, name: "BLE 2 Custom #4", name_ro: "BLE 2 Custom #4", unit: "-", multiplier: 1, category: "BLE", key: "ble_2_custom_4", desc_ro: "" },
  { id: 470, name: "BLE 2 Custom #5", name_ro: "BLE 2 Custom #5", unit: "-", multiplier: 1, category: "BLE", key: "ble_2_custom_5", desc_ro: "" },
  { id: 333, name: "BLE 3 Custom #1", name_ro: "BLE 3 Custom #1", unit: "-", multiplier: 1, category: "BLE", key: "ble_3_custom_1", desc_ro: "" },
  { id: 471, name: "BLE 3 Custom #2", name_ro: "BLE 3 Custom #2", unit: "-", multiplier: 1, category: "BLE", key: "ble_3_custom_2", desc_ro: "" },
  { id: 472, name: "BLE 3 Custom #3", name_ro: "BLE 3 Custom #3", unit: "-", multiplier: 1, category: "BLE", key: "ble_3_custom_3", desc_ro: "" },
  { id: 473, name: "BLE 3 Custom #4", name_ro: "BLE 3 Custom #4", unit: "-", multiplier: 1, category: "BLE", key: "ble_3_custom_4", desc_ro: "" },
  { id: 474, name: "BLE 3 Custom #5", name_ro: "BLE 3 Custom #5", unit: "-", multiplier: 1, category: "BLE", key: "ble_3_custom_5", desc_ro: "" },
  { id: 334, name: "BLE 4 Custom #1", name_ro: "BLE 4 Custom #1", unit: "-", multiplier: 1, category: "BLE", key: "ble_4_custom_1", desc_ro: "" },
  { id: 475, name: "BLE 4 Custom #2", name_ro: "BLE 4 Custom #2", unit: "-", multiplier: 1, category: "BLE", key: "ble_4_custom_2", desc_ro: "" },
  { id: 476, name: "BLE 4 Custom #3", name_ro: "BLE 4 Custom #3", unit: "-", multiplier: 1, category: "BLE", key: "ble_4_custom_3", desc_ro: "" },
  { id: 477, name: "BLE 4 Custom #4", name_ro: "BLE 4 Custom #4", unit: "-", multiplier: 1, category: "BLE", key: "ble_4_custom_4", desc_ro: "" },
  { id: 478, name: "BLE 4 Custom #5", name_ro: "BLE 4 Custom #5", unit: "-", multiplier: 1, category: "BLE", key: "ble_4_custom_5", desc_ro: "" },
  { id: 126, name: "Area of Harvest", name_ro: "Area of Harvest", unit: "m 2", multiplier: 1, category: "CAN", key: "can_area_of_harvest", desc_ro: "" },
  { id: 129, name: "Grain Moisture", name_ro: "Cereale umiditate", unit: "%", multiplier: 1, category: "CAN", key: "can_grain_moisture", desc_ro: "" },
  { id: 130, name: "Harvesting Drum RPM", name_ro: "Recoltare Drum turație", unit: "rpm", multiplier: 1, category: "CAN", key: "can_harvesting_drum_rpm", desc_ro: "" },
  { id: 131, name: "Gap Under Harvesting Drum", name_ro: "Gap Under recoltare Drum", unit: "mm", multiplier: 1, category: "CAN", key: "can_gap_under_harvesting_drum", desc_ro: "" },
  { id: 132, name: "Security State Flags", name_ro: "Securitate stare stegulețe", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 133, name: "Tachograph Total Vehicle Distance", name_ro: "Tachograph total Vehicle distanță", unit: "m", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 134, name: "Trip Distance", name_ro: "Trip distanță", unit: "m", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 140, name: "Driver 2 Continuous Driving Time", name_ro: "Șofer 2 Continuous condus timp", unit: "min.", multiplier: 1, category: "CAN", key: "can_driver_2_continuous_driving_time", desc_ro: "" },
  { id: 145, name: "Driver 1 Cumulative Driving Time", name_ro: "Șofer 1 Cumulative condus timp", unit: "min.", multiplier: 1, category: "CAN", key: "can_driver_1_cumulative_driving_time", desc_ro: "" },
  { id: 146, name: "Driver 2 Cumulative Driving Time", name_ro: "Șofer 2 Cumulative condus timp", unit: "min.", multiplier: 1, category: "CAN", key: "can_driver_2_cumulative_driving_time", desc_ro: "" },
  { id: 147, name: "Driver 1 ID High", name_ro: "Șofer 1 ID High", unit: "-", multiplier: 1, category: "CAN", key: "can_driver_1_id_high", desc_ro: "" },
  { id: 148, name: "Driver 1 ID Low", name_ro: "Șofer 1 ID Low", unit: "-", multiplier: 1, category: "CAN", key: "can_driver_1_id_low", desc_ro: "" },
  { id: 149, name: "Driver 2 ID High", name_ro: "Șofer 2 ID High", unit: "-", multiplier: 1, category: "CAN", key: "can_driver_2_id_high", desc_ro: "" },
  { id: 150, name: "Driver 2 ID Low", name_ro: "Șofer 2 ID Low", unit: "-", multiplier: 1, category: "CAN", key: "can_driver_2_id_low", desc_ro: "" },
  { id: 151, name: "Battery Temperature", name_ro: "Baterie temperatură", unit: "°C", multiplier: 0.1, category: "CAN", key: null, desc_ro: "" },
  { id: 152, name: "HV Battery Level", name_ro: "HV baterie nivel", unit: "%", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 177, name: "Amount Of Spread Gravel", name_ro: "Cantitate Of Spread Gravel", unit: "T", multiplier: 1, category: "CAN", key: "can_amount_of_spread_gravel", desc_ro: "" },
  { id: 304, name: "Vehicles Range On Battery", name_ro: "Vehicles autonomie On baterie", unit: "m", multiplier: 1, category: "CAN", key: "can_vehicles_range_on_battery", desc_ro: "" },
  { id: 305, name: "Vehicles Range On Additional Fuel", name_ro: "Vehicles autonomie On Additional combustibil", unit: "m", multiplier: 1, category: "CAN", key: "can_vehicles_range_on_additional_fuel", desc_ro: "" },
  { id: 325, name: "VIN", name_ro: "Serie șasiu (VIN)", unit: "-", multiplier: 1, category: "CAN", key: "can_vin_325", desc_ro: "" },
  { id: 282, name: "Fault Codes", name_ro: "Fault Codes", unit: "-", multiplier: 1, category: "Sistem", key: null, desc_ro: "" },
  { id: 517, name: "Security State Flags P4", name_ro: "Securitate stare stegulețe P4", unit: "-", multiplier: 1, category: "CAN", key: "can_security_state_flags_p4", desc_ro: "" },
  { id: 518, name: "Control State Flags P4", name_ro: "Control stare stegulețe P4", unit: "-", multiplier: 1, category: "CAN", key: "can_control_state_flags_p4", desc_ro: "" },
  { id: 519, name: "Indicator State Flags P4", name_ro: "Martor stare stegulețe P4", unit: "-", multiplier: 1, category: "CAN", key: "can_indicator_state_flags_p4", desc_ro: "" },
  { id: 520, name: "Agricultural State Flags P4", name_ro: "Agricol stare stegulețe P4", unit: "-", multiplier: 1, category: "Agricol", key: "can_agricultural_state_flags_p4", desc_ro: "" },
  { id: 521, name: "Utility State Flags P4", name_ro: "Utilitar stare stegulețe P4", unit: "-", multiplier: 1, category: "CAN", key: "can_utility_state_flags_p4", desc_ro: "" },
  { id: 522, name: "Cistern State Flags P4", name_ro: "Cisternă stare stegulețe P4", unit: "-", multiplier: 1, category: "CAN", key: "can_cistern_state_flags_p4", desc_ro: "" },
  { id: 855, name: "LNG Used", name_ro: "LNG Used", unit: "kg", multiplier: 1, category: "CAN", key: "can_lng_used", desc_ro: "" },
  { id: 856, name: "LNG Used (counted)", name_ro: "LNG Used (contorizat)", unit: "kg", multiplier: 1, category: "CAN", key: "can_lng_used_counted", desc_ro: "" },
  { id: 857, name: "LNG Level", name_ro: "LNG nivel", unit: "%", multiplier: 1, category: "CAN", key: "can_lng_level", desc_ro: "" },
  { id: 858, name: "LNG Level", name_ro: "LNG nivel", unit: "kg", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 1100, name: "Total LPG Used", name_ro: "Total GPL Used", unit: "l", multiplier: 1, category: "CAN", key: "can_total_lpg_used", desc_ro: "" },
  { id: 1101, name: "Total LPG Used Counted", name_ro: "Total GPL Used contorizat", unit: "l", multiplier: 1, category: "CAN", key: "can_total_lpg_used_counted", desc_ro: "" },
  { id: 1102, name: "LPG Level Proc", name_ro: "GPL nivel Proc", unit: "%", multiplier: 1, category: "CAN", key: "can_lpg_level_proc", desc_ro: "" },
  { id: 1103, name: "LPG Level Liters", name_ro: "GPL nivel Liters", unit: "l", multiplier: 1, category: "CAN", key: "can_lpg_level_liters", desc_ro: "" },
  { id: 898, name: "SSF Ignition", name_ro: "SSF Ignition", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 652, name: "SSF KeyInIgnitionLock", name_ro: "SSF KeyInIgnitionLock", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 899, name: "SSF Webasto", name_ro: "SSF Webasto", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_webasto", desc_ro: "" },
  { id: 900, name: "SSF Engine Working", name_ro: "SSF motor Working", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 901, name: "SSF Standalone Engine", name_ro: "SSF Standalone motor", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_standalone_engine", desc_ro: "" },
  { id: 902, name: "SSF Ready To Drive", name_ro: "SSF Ready To Drive", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 903, name: "SSF Engine Working On CNG", name_ro: "SSF motor Working On CNG", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_engine_working_on_cng", desc_ro: "" },
  { id: 904, name: "SSF Work Mode", name_ro: "SSF Work Mode", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 905, name: "SSF Operator", name_ro: "SSF Operator", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_operator", desc_ro: "" },
  { id: 906, name: "SSF Interlock", name_ro: "SSF Interlock", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_interlock", desc_ro: "" },
  { id: 907, name: "SSF Engine Lock Active", name_ro: "SSF motor Lock Active", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_engine_lock_active", desc_ro: "" },
  { id: 908, name: "SSF Request To Lock Engine", name_ro: "SSF Request To Lock motor", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_request_to_lock_engine", desc_ro: "" },
  { id: 653, name: "SSF Handbrake Is Active", name_ro: "SSF Handbrake Is Active", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_handbrake_is_active", desc_ro: "" },
  { id: 910, name: "SSF Footbrake Is Active", name_ro: "SSF Footbrake Is Active", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_footbrake_is_active", desc_ro: "" },
  { id: 911, name: "SSF Clutch Pushed", name_ro: "SSF Clutch Pushed", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_clutch_pushed", desc_ro: "" },
  { id: 912, name: "SSF Hazard Warning Lights", name_ro: "SSF Hazard Warning Lights", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_hazard_warning_lights", desc_ro: "" },
  { id: 654, name: "SSF Front Left Door Open", name_ro: "SSF Front Left ușă Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_front_left_door_open", desc_ro: "" },
  { id: 655, name: "SSF Front Right Door Open", name_ro: "SSF Front Right ușă Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_front_right_door_open", desc_ro: "" },
  { id: 656, name: "SSF Rear Left Door Open", name_ro: "SSF Rear Left ușă Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_rear_left_door_open", desc_ro: "" },
  { id: 657, name: "SSF Rear Right Door Open", name_ro: "SSF Rear Right ușă Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_rear_right_door_open", desc_ro: "" },
  { id: 658, name: "SSF Trunk Door Open", name_ro: "SSF Trunk ușă Open", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 913, name: "SSF Engine Cover Open", name_ro: "SSF motor Cover Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_engine_cover_open", desc_ro: "" },
  { id: 909, name: "SSF Roof Open", name_ro: "SSF Roof Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_roof_open", desc_ro: "" },
  { id: 914, name: "SSF Charging Wire Plugged", name_ro: "SSF Charging Wire Plugged", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_charging_wire_plugged", desc_ro: "" },
  { id: 915, name: "SSF Batttery Charging", name_ro: "SSF Batttery Charging", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_batttery_charging", desc_ro: "" },
  { id: 916, name: "SSF Electric Engine State", name_ro: "SSF Electric motor stare", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_electric_engine_state", desc_ro: "" },
  { id: 917, name: "SSF Car Closed Factory Remote", name_ro: "SSF Car Closed Factory Remote", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_car_closed_factory_remote", desc_ro: "" },
  { id: 662, name: "SSF Car Is Closed", name_ro: "SSF Car Is Closed", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_car_is_closed", desc_ro: "" },
  { id: 918, name: "SSF Factory Alarm Actuated", name_ro: "SSF Factory Alarm Actuated", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_factory_alarm_actuated", desc_ro: "" },
  { id: 919, name: "SSF Factory Alarm Emulated", name_ro: "SSF Factory Alarm Emulated", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_factory_alarm_emulated", desc_ro: "" },
  { id: 920, name: "SSF Signal Close Factory Remote", name_ro: "SSF Signal Close Factory Remote", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_signal_close_factory_remote", desc_ro: "" },
  { id: 921, name: "SSF Signal Open Factory Remote", name_ro: "SSF Signal Open Factory Remote", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_signal_open_factory_remote", desc_ro: "" },
  { id: 922, name: "SSF Rearming Signal", name_ro: "SSF Rearming Signal", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_rearming_signal", desc_ro: "" },
  { id: 923, name: "SSF Trunk Door Opened Factory Remote", name_ro: "SSF Trunk ușă Opened Factory Remote", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_trunk_door_opened_factory_remote", desc_ro: "" },
  { id: 924, name: "SSF CAN Module In Sleep", name_ro: "SSF CAN Module In Sleep", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_can_module_in_sleep", desc_ro: "" },
  { id: 925, name: "SSF Factory Remote 3x", name_ro: "SSF Factory Remote 3x", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_factory_remote_3x", desc_ro: "" },
  { id: 926, name: "SSF Factory Armed", name_ro: "SSF Factory Armed", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_factory_armed", desc_ro: "" },
  { id: 660, name: "SSF Parking Gear Active (automatic gear box)", name_ro: "SSF Parking treaptă viteză Active (automatic treaptă viteză box)", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 661, name: "SSF Reverse Gear Active", name_ro: "SSF Reverse treaptă viteză Active", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 659, name: "SSF Neutral Gear Active (automatic gear box)", name_ro: "SSF Neutral treaptă viteză Active (automatic treaptă viteză box)", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 927, name: "SSF Drive Is Active (automatic gear box)", name_ro: "SSF Drive Is Active (automatic treaptă viteză box)", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_drive_is_active_automatic_gear_box", desc_ro: "" },
  { id: 1083, name: "SSF Engine Working On Dual Fuel", name_ro: "SSF motor Working On Dual combustibil", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_engine_working_on_dual_fuel", desc_ro: "" },
  { id: 1084, name: "SSF Engine Working On LPG", name_ro: "SSF motor Working On GPL", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_engine_working_on_lpg", desc_ro: "" },
  { id: 928, name: "CSF Parking Lights", name_ro: "CSF Parking Lights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_parking_lights", desc_ro: "" },
  { id: 929, name: "CSF Dipped Head lights", name_ro: "CSF Dipped Head lights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_dipped_head_lights", desc_ro: "" },
  { id: 930, name: "CSF Full Beam Headlights", name_ro: "CSF Full Beam Headlights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_full_beam_headlights", desc_ro: "" },
  { id: 931, name: "CSF Rear Fog Lights", name_ro: "CSF Rear Fog Lights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_rear_fog_lights", desc_ro: "" },
  { id: 932, name: "CSF Front Fog Lights", name_ro: "CSF Front Fog Lights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_front_fog_lights", desc_ro: "" },
  { id: 933, name: "CSF Additional Front Lights", name_ro: "CSF Additional Front Lights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_additional_front_lights", desc_ro: "" },
  { id: 934, name: "CSF Additional Rear Lights", name_ro: "CSF Additional Rear Lights", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_additional_rear_lights", desc_ro: "" },
  { id: 935, name: "CSF Light Signal", name_ro: "CSF Light Signal", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_light_signal", desc_ro: "" },
  { id: 936, name: "CSF Air Conditioning", name_ro: "CSF Air Conditioning", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_air_conditioning", desc_ro: "" },
  { id: 937, name: "CSF Cruise Control", name_ro: "CSF tempomat control", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_cruise_control", desc_ro: "" },
  { id: 938, name: "CSF Automatic Retarder", name_ro: "CSF Automatic retarder", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_automatic_retarder", desc_ro: "" },
  { id: 939, name: "CSF Manual Retarder", name_ro: "CSF Manual retarder", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_manual_retarder", desc_ro: "" },
  { id: 940, name: "CSF Driver's Seatbelt Fastened", name_ro: "CSF șofer's Seatbelt Fastened", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_driver_s_seatbelt_fastened", desc_ro: "" },
  { id: 941, name: "CSF Front Driver's Seatbelt Fastened", name_ro: "CSF Front șofer's Seatbelt Fastened", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_front_driver_s_seatbelt_fastened", desc_ro: "" },
  { id: 942, name: "CSF Left Driver's Seatbelt Fastened", name_ro: "CSF Left șofer's Seatbelt Fastened", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_left_driver_s_seatbelt_fastened", desc_ro: "" },
  { id: 943, name: "CSF Right Driver's Seatbelt Fastened", name_ro: "CSF Right șofer's Seatbelt Fastened", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_right_driver_s_seatbelt_fastened", desc_ro: "" },
  { id: 944, name: "CSF Centre Driver's Seatbelt Fastened", name_ro: "CSF Centre șofer's Seatbelt Fastened", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_centre_driver_s_seatbelt_fastened", desc_ro: "" },
  { id: 945, name: "CSF Front Passenger Present", name_ro: "CSF Front Passenger Present", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_front_passenger_present", desc_ro: "" },
  { id: 946, name: "CSF PTO", name_ro: "CSF PTO", unit: "-", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 947, name: "CSF Front Differential Locked", name_ro: "CSF Front Differential Locked", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_front_differential_locked", desc_ro: "" },
  { id: 948, name: "CSF Rear Differential Locked", name_ro: "CSF Rear Differential Locked", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_rear_differential_locked", desc_ro: "" },
  { id: 949, name: "CSF Central Differential 4HI Locked", name_ro: "CSF Central Differential 4HI Locked", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_central_differential_4hi_locked", desc_ro: "" },
  { id: 950, name: "CSF Central Differential 4LO Locked", name_ro: "CSF Central Differential 4LO Locked", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_central_differential_4lo_locked", desc_ro: "" },
  { id: 951, name: "CSF Trailer Axle 1 Lift Active", name_ro: "CSF remorcă axă 1 Lift Active", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_trailer_axle_1_lift_active", desc_ro: "" },
  { id: 952, name: "CSF Trailer Axle 2 Lift Active", name_ro: "CSF remorcă axă 2 Lift Active", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_trailer_axle_2_lift_active", desc_ro: "" },
  { id: 1085, name: "CSF Trailer Connected", name_ro: "CSF remorcă Connected", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_trailer_connected", desc_ro: "" },
  { id: 1086, name: "CSF Start Stop System Inactive", name_ro: "CSF Start Stop System Inactive", unit: "-", multiplier: 1, category: "CAN", key: "can_csf_start_stop_system_inactive", desc_ro: "" },
  { id: 953, name: "ISF Check Engine Indicator", name_ro: "ISF Check motor martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_check_engine_indicator", desc_ro: "" },
  { id: 954, name: "ISF ABS Indicator", name_ro: "ISF ABS martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_abs_indicator", desc_ro: "" },
  { id: 955, name: "ISF ESP Indicator", name_ro: "ISF ESP martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_esp_indicator", desc_ro: "" },
  { id: 956, name: "ISF ESP Turned Off", name_ro: "ISF ESP Turned Off", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_esp_turned_off", desc_ro: "" },
  { id: 957, name: "ISF Stop Indicator", name_ro: "ISF Stop martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_stop_indicator", desc_ro: "" },
  { id: 958, name: "ISF Oil Level Indicator", name_ro: "ISF ulei nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_oil_level_indicator", desc_ro: "" },
  { id: 959, name: "ISF Coolant liquid level", name_ro: "ISF lichid răcire liquid nivel", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_coolant_liquid_level", desc_ro: "" },
  { id: 960, name: "ISF Battery Not Charging Indicator", name_ro: "ISF baterie Not Charging martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_battery_not_charging_indicator", desc_ro: "" },
  { id: 961, name: "ISF Handbrake System Indicator", name_ro: "ISF Handbrake System martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_handbrake_system_indicator", desc_ro: "" },
  { id: 962, name: "ISF AIRBAG Indicator", name_ro: "ISF AIRBAG martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_airbag_indicator", desc_ro: "" },
  { id: 963, name: "ISF EPS Indicator", name_ro: "ISF EPS martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_eps_indicator", desc_ro: "" },
  { id: 964, name: "ISF Warning Indicator", name_ro: "ISF Warning martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_warning_indicator", desc_ro: "" },
  { id: 965, name: "ISF Lights Failure Indicator", name_ro: "ISF Lights Failure martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_lights_failure_indicator", desc_ro: "" },
  { id: 966, name: "ISF Low Tire Pressure Indicator", name_ro: "ISF Low Tire presiune martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_tire_pressure_indicator", desc_ro: "" },
  { id: 967, name: "ISF Wear Of Brake Pads Indicator", name_ro: "ISF uzură Of frână Pads martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_wear_of_brake_pads_indicator", desc_ro: "" },
  { id: 968, name: "ISF Low Fuel Level Indicator", name_ro: "ISF Low combustibil nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_fuel_level_indicator", desc_ro: "" },
  { id: 969, name: "ISF Maintenence required Indicator", name_ro: "ISF Maintenence required martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_maintenence_required_indicator", desc_ro: "" },
  { id: 970, name: "ISF Glow Plug Indicator", name_ro: "ISF Glow Plug martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_glow_plug_indicator", desc_ro: "" },
  { id: 971, name: "ISF FAP Indicator", name_ro: "ISF FAP martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_fap_indicator", desc_ro: "" },
  { id: 972, name: "ISF EPC (Electronic Power Control) Indicator", name_ro: "ISF EPC (Electronic Power control) martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_epc_electronic_power_control_indicator", desc_ro: "" },
  { id: 973, name: "ISF Clogged Engine Oil Filter Indicator", name_ro: "ISF Clogged motor ulei Filter martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_clogged_engine_oil_filter_indicator", desc_ro: "" },
  { id: 974, name: "ISF Low Engine Oil Pressure Indicator", name_ro: "ISF Low motor ulei presiune martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_engine_oil_pressure_indicator", desc_ro: "" },
  { id: 975, name: "ISF Too High Engine Oil Temperature Indicator", name_ro: "ISF Too High motor ulei temperatură martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_too_high_engine_oil_temperature_indicator", desc_ro: "" },
  { id: 976, name: "ISF Low Coolant Level Indicator", name_ro: "ISF Low lichid răcire nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_coolant_level_indicator", desc_ro: "" },
  { id: 977, name: "ISF Clogged Hydraulic System Oil filter Indicator", name_ro: "ISF Clogged Hydraulic System ulei filter martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_clogged_hydraulic_system_oil_filter_indicator", desc_ro: "" },
  { id: 978, name: "ISF Hydraulic System Low Pressure Indicator", name_ro: "ISF Hydraulic System Low presiune martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_hydraulic_system_low_pressure_indicator", desc_ro: "" },
  { id: 979, name: "ISF Hydraulic Oil Low Level Indicator", name_ro: "ISF Hydraulic ulei Low nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_hydraulic_oil_low_level_indicator", desc_ro: "" },
  { id: 980, name: "ISF Hydraulic System High Temperature Indicator", name_ro: "ISF Hydraulic System High temperatură martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_hydraulic_system_high_temperature_indicator", desc_ro: "" },
  { id: 981, name: "ISF Oil Overflow In Hydraulic Chamber Indicator", name_ro: "ISF ulei Overflow In Hydraulic Chamber martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_oil_overflow_in_hydraulic_chamber_indicator", desc_ro: "" },
  { id: 982, name: "ISF Clogged Air Filter Indicator", name_ro: "ISF Clogged Air Filter martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_clogged_air_filter_indicator", desc_ro: "" },
  { id: 983, name: "ISF Clogged Fuel Filter Indicator", name_ro: "ISF Clogged combustibil Filter martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_clogged_fuel_filter_indicator", desc_ro: "" },
  { id: 984, name: "ISF Water in Fuel Indicator", name_ro: "ISF Water in combustibil martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_water_in_fuel_indicator", desc_ro: "" },
  { id: 985, name: "ISF Clogged Brake System Filter Indicator", name_ro: "ISF Clogged frână System Filter martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_clogged_brake_system_filter_indicator", desc_ro: "" },
  { id: 986, name: "ISF Low Washer Fluid Level Indicator", name_ro: "ISF Low Washer Fluid nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_washer_fluid_level_indicator", desc_ro: "" },
  { id: 987, name: "ISF Low AdBlue Level Indicator", name_ro: "ISF Low AdBlue nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_adblue_level_indicator", desc_ro: "" },
  { id: 988, name: "ISF Low Trailer Tyre Pressure Indicator", name_ro: "ISF Low remorcă Tyre presiune martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_trailer_tyre_pressure_indicator", desc_ro: "" },
  { id: 989, name: "ISF Wear Of Trailer Brake Lining Indicator", name_ro: "ISF uzură Of remorcă frână Lining martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_wear_of_trailer_brake_lining_indicator", desc_ro: "" },
  { id: 990, name: "ISF High Trailer Brake Temperature Indicator", name_ro: "ISF High remorcă frână temperatură martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_high_trailer_brake_temperature_indicator", desc_ro: "" },
  { id: 991, name: "ISF Incorrect Trailer Pneumatic Supply Indicator", name_ro: "ISF Incorrect remorcă Pneumatic Supply martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_incorrect_trailer_pneumatic_supply_indicator", desc_ro: "" },
  { id: 992, name: "ISF Low CNG Level Indicator", name_ro: "ISF Low CNG nivel martor", unit: "-", multiplier: 1, category: "CAN", key: "can_isf_low_cng_level_indicator", desc_ro: "" },
  { id: 993, name: "ASF Right Joystick Moved Right Active", name_ro: "ASF Right Joystick Moved Right Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_right_joystick_moved_right_active", desc_ro: "" },
  { id: 994, name: "ASF Right Joystick Moved Left Active", name_ro: "ASF Right Joystick Moved Left Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_right_joystick_moved_left_active", desc_ro: "" },
  { id: 995, name: "ASF Right Joystick Moved Forward Active", name_ro: "ASF Right Joystick Moved Forward Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_right_joystick_moved_forward_active", desc_ro: "" },
  { id: 996, name: "ASF Right Joystick Moved Back Active", name_ro: "ASF Right Joystick Moved Back Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_right_joystick_moved_back_active", desc_ro: "" },
  { id: 997, name: "ASF Left Joystick Moved Right Active", name_ro: "ASF Left Joystick Moved Right Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_left_joystick_moved_right_active", desc_ro: "" },
  { id: 998, name: "ASF Left Joystick Moved Left Active", name_ro: "ASF Left Joystick Moved Left Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_left_joystick_moved_left_active", desc_ro: "" },
  { id: 999, name: "ASF Left Joystick Moved Forward Active", name_ro: "ASF Left Joystick Moved Forward Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_left_joystick_moved_forward_active", desc_ro: "" },
  { id: 1000, name: "ASF Left Joystick Moved Back Active", name_ro: "ASF Left Joystick Moved Back Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_left_joystick_moved_back_active", desc_ro: "" },
  { id: 1001, name: "ASF First Rear hydraulic", name_ro: "ASF First Rear hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_first_rear_hydraulic", desc_ro: "" },
  { id: 1002, name: "ASF Second Rear hydraulic", name_ro: "ASF Second Rear hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_second_rear_hydraulic", desc_ro: "" },
  { id: 1003, name: "ASF Third Rear hydraulic", name_ro: "ASF Third Rear hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_third_rear_hydraulic", desc_ro: "" },
  { id: 1004, name: "ASF Fourth Rear hydraulic", name_ro: "ASF Fourth Rear hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_fourth_rear_hydraulic", desc_ro: "" },
  { id: 1005, name: "ASF First Front hydraulic", name_ro: "ASF First Front hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_first_front_hydraulic", desc_ro: "" },
  { id: 1006, name: "ASF Second Front hydraulic", name_ro: "ASF Second Front hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_second_front_hydraulic", desc_ro: "" },
  { id: 1007, name: "ASF Third Front hydraulic", name_ro: "ASF Third Front hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_third_front_hydraulic", desc_ro: "" },
  { id: 1008, name: "ASF Fourth Front hydraulic", name_ro: "ASF Fourth Front hydraulic", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_fourth_front_hydraulic", desc_ro: "" },
  { id: 1009, name: "ASF Front Three-point Hitch", name_ro: "ASF Front Three-point Hitch", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_front_three_point_hitch", desc_ro: "" },
  { id: 1010, name: "ASF Rear Three-point Hitch", name_ro: "ASF Rear Three-point Hitch", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_rear_three_point_hitch", desc_ro: "" },
  { id: 1011, name: "ASF Front Power Take-off", name_ro: "ASF Front Power Take-off", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_front_power_take_off", desc_ro: "" },
  { id: 1012, name: "ASF Rear Power Take-off", name_ro: "ASF Rear Power Take-off", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_rear_power_take_off", desc_ro: "" },
  { id: 1013, name: "ASF Mowing Active", name_ro: "ASF Mowing Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_mowing_active", desc_ro: "" },
  { id: 1014, name: "ASF Threshing Active", name_ro: "ASF Threshing Active", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_threshing_active", desc_ro: "" },
  { id: 1015, name: "ASF Grain Release From Hopper", name_ro: "ASF cereale Release From Hopper", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_grain_release_from_hopper", desc_ro: "" },
  { id: 1016, name: "ASF Grain Tank Is 100% Full", name_ro: "ASF cereale rezervor Is 100% Full", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_grain_tank_is_100_full", desc_ro: "" },
  { id: 1017, name: "ASF Grain Tank Is 70% Full", name_ro: "ASF cereale rezervor Is 70% Full", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_grain_tank_is_70_full", desc_ro: "" },
  { id: 1018, name: "ASF Grain Tank Is Opened", name_ro: "ASF cereale rezervor Is Opened", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_grain_tank_is_opened", desc_ro: "" },
  { id: 1019, name: "ASF Unloader Drive", name_ro: "ASF Unloader Drive", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_unloader_drive", desc_ro: "" },
  { id: 1020, name: "ASF Cleaning Fan Control Turned Off", name_ro: "ASF Cleaning Fan control Turned Off", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_cleaning_fan_control_turned_off", desc_ro: "" },
  { id: 1021, name: "ASF Threshing Drum Control Turned Off", name_ro: "ASF Threshing Drum control Turned Off", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_threshing_drum_control_turned_off", desc_ro: "" },
  { id: 1022, name: "ASF Straw Walker Is Clogged", name_ro: "ASF Straw Walker Is Clogged", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_straw_walker_is_clogged", desc_ro: "" },
  { id: 1023, name: "ASF Excessive Clearance Under The Threshing Drum", name_ro: "ASF Excessive Clearance Under The Threshing Drum", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_excessive_clearance_under_the_threshing_drum", desc_ro: "" },
  { id: 1024, name: "ASF Low Temperature Of Drive System Hydraulics Less Than 5 Grades", name_ro: "ASF Low temperatură Of Drive System Hydraulics Less Than 5 Grades", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_low_temperature_of_drive_system_hydraulics_less_than_5_grades", desc_ro: "" },
  { id: 1025, name: "ASF High Temperature Of Drive System Hydraulics Greater Than 86 Grades", name_ro: "ASF High temperatură Of Drive System Hydraulics Greater Than 86 Grades", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_high_temperature_of_drive_system_hydraulics_greater_than_86_grades", desc_ro: "" },
  { id: 1026, name: "ASF Ear Auger Speed Below The Norm", name_ro: "ASF Ear Auger viteză Below The Norm", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_ear_auger_speed_below_the_norm", desc_ro: "" },
  { id: 1027, name: "ASF Grain Auger Speed Below The Norm", name_ro: "ASF cereale Auger viteză Below The Norm", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_grain_auger_speed_below_the_norm", desc_ro: "" },
  { id: 1028, name: "ASF Straw Chooper Speed Below The Norm", name_ro: "ASF Straw Chooper viteză Below The Norm", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_straw_chooper_speed_below_the_norm", desc_ro: "" },
  { id: 1029, name: "ASF Straw Shaker Speed Below The Norm", name_ro: "ASF Straw Shaker viteză Below The Norm", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_straw_shaker_speed_below_the_norm", desc_ro: "" },
  { id: 1030, name: "ASF Feeder Speed Below The Norm", name_ro: "ASF Feeder viteză Below The Norm", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_feeder_speed_below_the_norm", desc_ro: "" },
  { id: 1031, name: "ASF Straw Chopper Switched On", name_ro: "ASF Straw Chopper Switched On", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_straw_chopper_switched_on", desc_ro: "" },
  { id: 1032, name: "ASF Corn Header Connected", name_ro: "ASF Corn Header Connected", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_corn_header_connected", desc_ro: "" },
  { id: 1033, name: "ASF Grain Header Connected", name_ro: "ASF cereale Header Connected", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_grain_header_connected", desc_ro: "" },
  { id: 1034, name: "ASF Feeder Reverse Switched On", name_ro: "ASF Feeder Reverse Switched On", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_feeder_reverse_switched_on", desc_ro: "" },
  { id: 1035, name: "ASF The Pressure Filter Of The Hydraulic Pump Is Clogged", name_ro: "ASF The presiune Filter Of The Hydraulic Pump Is Clogged", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_the_pressure_filter_of_the_hydraulic_pump_is_clogged", desc_ro: "" },
  { id: 1087, name: "ASF Adapter Pressure Filter Sensor", name_ro: "ASF Adapter presiune Filter senzor", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_adapter_pressure_filter_sensor", desc_ro: "" },
  { id: 1088, name: "ASF Service 2 Required Indicator", name_ro: "ASF Service 2 Required martor", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_service_2_required_indicator", desc_ro: "" },
  { id: 1089, name: "ASF Drain Filter Clogged Indicator", name_ro: "ASF Drain Filter Clogged martor", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_drain_filter_clogged_indicator", desc_ro: "" },
  { id: 1090, name: "ASF Section 1 Spraying", name_ro: "ASF secțiune 1 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_1_spraying", desc_ro: "" },
  { id: 1091, name: "ASF Section 2 Spraying", name_ro: "ASF secțiune 2 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_2_spraying", desc_ro: "" },
  { id: 1092, name: "ASF Section 3 Spraying", name_ro: "ASF secțiune 3 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_3_spraying", desc_ro: "" },
  { id: 1093, name: "ASF Section 4 Spraying", name_ro: "ASF secțiune 4 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_4_spraying", desc_ro: "" },
  { id: 1094, name: "ASF Section 5 Spraying", name_ro: "ASF secțiune 5 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_5_spraying", desc_ro: "" },
  { id: 1095, name: "ASF Section 6 Spraying", name_ro: "ASF secțiune 6 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_6_spraying", desc_ro: "" },
  { id: 1096, name: "ASF Section 7 Spraying", name_ro: "ASF secțiune 7 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_7_spraying", desc_ro: "" },
  { id: 1097, name: "ASF Section 8 Spraying", name_ro: "ASF secțiune 8 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_8_spraying", desc_ro: "" },
  { id: 1098, name: "ASF Section 9 Spraying", name_ro: "ASF secțiune 9 Spraying", unit: "-", multiplier: 1, category: "CAN", key: "can_asf_section_9_spraying", desc_ro: "" },
  { id: 1036, name: "USF Spreading", name_ro: "USF împrăștiere", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_spreading", desc_ro: "" },
  { id: 1037, name: "USF Pouring Chemicals", name_ro: "USF Pouring Chemicals", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_pouring_chemicals", desc_ro: "" },
  { id: 1038, name: "USF Conveyor Belt", name_ro: "USF Conveyor Belt", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_conveyor_belt", desc_ro: "" },
  { id: 1039, name: "USF Salt Spreader's Drive Wheel", name_ro: "USF sare Spreader's Drive roată", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_salt_spreader_s_drive_wheel", desc_ro: "" },
  { id: 1040, name: "USF Brushes", name_ro: "USF Brushes", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_brushes", desc_ro: "" },
  { id: 1041, name: "USF Vacuum Cleaner", name_ro: "USF Vacuum Cleaner", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_vacuum_cleaner", desc_ro: "" },
  { id: 1042, name: "USF Water Supply", name_ro: "USF Water Supply", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_water_supply", desc_ro: "" },
  { id: 1043, name: "USF KarcherOn", name_ro: "USF KarcherOn", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_karcheron", desc_ro: "" },
  { id: 1044, name: "USF Liquid pump", name_ro: "USF Liquid pump", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_liquid_pump", desc_ro: "" },
  { id: 1045, name: "USF Unloading From The Hopper", name_ro: "USF Unloading From The Hopper", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_unloading_from_the_hopper", desc_ro: "" },
  { id: 1046, name: "USF Low Salt (Sand) Level In Container Indicator", name_ro: "USF Low sare (Sand) nivel In Container martor", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_low_salt_sand_level_in_container_indicator", desc_ro: "" },
  { id: 1047, name: "USF Low Water Level in Container Indicator", name_ro: "USF Low Water nivel in Container martor", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_low_water_level_in_container_indicator", desc_ro: "" },
  { id: 1048, name: "USF Chemicals", name_ro: "USF Chemicals", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_chemicals", desc_ro: "" },
  { id: 1049, name: "USF Compressor", name_ro: "USF Compressor", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_compressor", desc_ro: "" },
  { id: 1050, name: "USF Water Valve Is Opened", name_ro: "USF Water Valve Is Opened", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_water_valve_is_opened", desc_ro: "" },
  { id: 1051, name: "USF Cabin Moved Up Status Active", name_ro: "USF Cabin Moved Up stare Active", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_cabin_moved_up_status_active", desc_ro: "" },
  { id: 1052, name: "USF Cabin Moved Down Status Active", name_ro: "USF Cabin Moved Down stare Active", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_cabin_moved_down_status_active", desc_ro: "" },
  { id: 1099, name: "USF Hydraulics Work Not Permitted", name_ro: "USF Hydraulics Work Not Permitted", unit: "-", multiplier: 1, category: "CAN", key: "can_usf_hydraulics_work_not_permitted", desc_ro: "" },
  { id: 1053, name: "CiSF Section 1 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 1 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_1_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1054, name: "CiSF Section 1 Filled", name_ro: "CiSF secțiune 1 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_1_filled", desc_ro: "" },
  { id: 1055, name: "CiSF Section 1 Overfilled", name_ro: "CiSF secțiune 1 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_1_overfilled", desc_ro: "" },
  { id: 1056, name: "CiSF Section 2 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 2 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_2_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1057, name: "CiSF Section 2 Filled", name_ro: "CiSF secțiune 2 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_2_filled", desc_ro: "" },
  { id: 1058, name: "CiSF Section 2 Overfilled", name_ro: "CiSF secțiune 2 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_2_overfilled", desc_ro: "" },
  { id: 1059, name: "CiSF Section 3 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 3 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_3_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1060, name: "CiSF Section 3 Filled", name_ro: "CiSF secțiune 3 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_3_filled", desc_ro: "" },
  { id: 1061, name: "CiSF Section 3 Overfilled", name_ro: "CiSF secțiune 3 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_3_overfilled", desc_ro: "" },
  { id: 1062, name: "CiSF Section 4 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 4 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_4_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1063, name: "CiSF Section 4 Filled", name_ro: "CiSF secțiune 4 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_4_filled", desc_ro: "" },
  { id: 1064, name: "CiSF Section 4 Overfilled", name_ro: "CiSF secțiune 4 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_4_overfilled", desc_ro: "" },
  { id: 1065, name: "CiSF Section 5 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 5 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_5_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1066, name: "CiSF Section 5 Filled", name_ro: "CiSF secțiune 5 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_5_filled", desc_ro: "" },
  { id: 1067, name: "CiSF Section 5 Overfilled", name_ro: "CiSF secțiune 5 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_5_overfilled", desc_ro: "" },
  { id: 1068, name: "CiSF Section 6 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 6 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_6_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1069, name: "CiSF Section 6 Filled", name_ro: "CiSF secțiune 6 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_6_filled", desc_ro: "" },
  { id: 1070, name: "CiSF Section 6 Overfilled", name_ro: "CiSF secțiune 6 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_6_overfilled", desc_ro: "" },
  { id: 1071, name: "CiSF Section 7 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 7 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_7_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1072, name: "CiSF Section 7 Filled", name_ro: "CiSF secțiune 7 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_7_filled", desc_ro: "" },
  { id: 1073, name: "CiSF Section 7 Overfilled", name_ro: "CiSF secțiune 7 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_7_overfilled", desc_ro: "" },
  { id: 1074, name: "CiSF Section 8 Presence Of Fluid In The Downpipe", name_ro: "CiSF secțiune 8 Presence Of Fluid In The Downpipe", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_8_presence_of_fluid_in_the_downpipe", desc_ro: "" },
  { id: 1075, name: "CiSF Section 8 Filled", name_ro: "CiSF secțiune 8 umplut", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_8_filled", desc_ro: "" },
  { id: 1076, name: "CiSF Section 8 Overfilled", name_ro: "CiSF secțiune 8 Overfilled", unit: "-", multiplier: 1, category: "CAN", key: "can_cisf_section_8_overfilled", desc_ro: "" },
  { id: 450, name: "CNG Level Kg", name_ro: "CNG nivel Kg", unit: "Kg", multiplier: 10, category: "CAN", key: "can_cng_level_kg", desc_ro: "" },
  { id: 859, name: "Distance from need of service", name_ro: "Distanță from need of service", unit: "km", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 860, name: "Distance from last service", name_ro: "Distanță from last service", unit: "km", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 861, name: "Time to next service", name_ro: "Timp to next service", unit: "day", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 862, name: "Time from need of service", name_ro: "Timp from need of service", unit: "day", multiplier: 1, category: "CAN", key: "can_time_from_need_of_service", desc_ro: "" },
  { id: 863, name: "Time from last serivce", name_ro: "Timp from last serivce", unit: "day", multiplier: 1, category: "CAN", key: "can_time_from_last_serivce", desc_ro: "" },
  { id: 864, name: "Distance to next oil service", name_ro: "Distanță to next ulei service", unit: "km", multiplier: 1, category: "CAN", key: "can_distance_to_next_oil_service", desc_ro: "" },
  { id: 865, name: "Time to next oil service", name_ro: "Timp to next ulei service", unit: "day", multiplier: 1, category: "CAN", key: "can_time_to_next_oil_service", desc_ro: "" },
  { id: 866, name: "LVCAN Vehicle Range", name_ro: "LVCAN Vehicle autonomie", unit: "km", multiplier: 1, category: "CAN", key: "can_lvcan_vehicle_range", desc_ro: "" },
  { id: 867, name: "LVCAN Total CNG counted", name_ro: "LVCAN total CNG contorizat", unit: "kg", multiplier: 1, category: "CAN", key: "can_lvcan_total_cng_counted", desc_ro: "" },
  { id: 1079, name: "Total Bale Count", name_ro: "Total Bale număr", unit: "-", multiplier: 1, category: "CAN", key: "can_total_bale_count", desc_ro: "" },
  { id: 1080, name: "Bale Count", name_ro: "Bale număr", unit: "-", multiplier: 1, category: "CAN", key: "can_bale_count", desc_ro: "" },
  { id: 1081, name: "Cut Bale Count", name_ro: "Cut Bale număr", unit: "-", multiplier: 1, category: "CAN", key: "can_cut_bale_count", desc_ro: "" },
  { id: 1082, name: "Bale Slices", name_ro: "Bale Slices", unit: "-", multiplier: 1, category: "CAN", key: "can_bale_slices", desc_ro: "" },
  { id: 1116, name: "LVCAN MaxRoadSpeed", name_ro: "LVCAN MaxRoadSpeed", unit: "km/h", multiplier: 1, category: "CAN", key: null, desc_ro: "" },
  { id: 1117, name: "LVCAN ExceededRoadSpeed", name_ro: "LVCAN ExceededRoadSpeed", unit: "km/h", multiplier: 1, category: "CAN", key: "can_lvcan_exceededroadspeed", desc_ro: "" },
  { id: 1205, name: "LVCAN RSF SpeedLimitSign", name_ro: "LVCAN RSF SpeedLimitSign", unit: "-", multiplier: 1, category: "CAN", key: "can_lvcan_rsf_speedlimitsign", desc_ro: "" },
  { id: 1206, name: "LVCAN RSF EndOfSpeedLimitSign", name_ro: "LVCAN RSF EndOfSpeedLimitSign", unit: "-", multiplier: 1, category: "CAN", key: "can_lvcan_rsf_endofspeedlimitsign", desc_ro: "" },
  { id: 1207, name: "LVCAN RSF SpeedExceeded", name_ro: "LVCAN RSF SpeedExceeded", unit: "-", multiplier: 1, category: "CAN", key: "can_lvcan_rsf_speedexceeded", desc_ro: "" },
  { id: 1208, name: "LVCAN RSF TimeSpeedLimitSign", name_ro: "LVCAN RSF TimeSpeedLimitSign", unit: "-", multiplier: 1, category: "CAN", key: "can_lvcan_rsf_timespeedlimitsign", desc_ro: "" },
  { id: 1209, name: "LVCAN RSF WthrSpeedLimitSign", name_ro: "LVCAN RSF WthrSpeedLimitSign", unit: "-", multiplier: 1, category: "CAN", key: "can_lvcan_rsf_wthrspeedlimitsign", desc_ro: "" },
  { id: 1211, name: "SSF Front Left Window Open", name_ro: "SSF Front Left Window Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_front_left_window_open", desc_ro: "" },
  { id: 1212, name: "SSF Front Right Window Open", name_ro: "SSF Front Right Window Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_front_right_window_open", desc_ro: "" },
  { id: 1213, name: "SSF Rear Left Window Open", name_ro: "SSF Rear Left Window Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_rear_left_window_open", desc_ro: "" },
  { id: 1214, name: "SSF Rear Right Window Open", name_ro: "SSF Rear Right Window Open", unit: "-", multiplier: 1, category: "CAN", key: "can_ssf_rear_right_window_open", desc_ro: "" },
];
