// io_names_extra.js — GENERAT de tools/gen-io-extra.js din specul oficial Teltonika FMC130.
// NU edita de mână: rulează generatorul după ce actualizezi tools/fixtures/avl-fmc130.json.
// Harta scrisă de mână din codec8e.js are prioritate; aici e restul listei oficiale (511 ID-uri),
// ca un Passat cu ALL-CAN300 să nu mai apară cu zeci de „io_517" nedescifrate.
// Câmpuri: name (cheia din io_data) · mult (multiplicator afișare/conversie) · semnat (two's complement)
//          · octeti (lățimea valorii) · unit · comentariu = numele oficial + grupul din spec.
module.exports = {
  4: { name: 'pulse_counter_din1', octeti: 4 }, // Pulse Counter Din1 [Permanent I/O elements]
  5: { name: 'pulse_counter_din2', octeti: 4 }, // Pulse Counter Din2 [Permanent I/O elements]
  13: { name: 'fuel_rate_gps', mult: 0.01, octeti: 2, unit: "l/100km" }, // Fuel Rate GPS [Permanent I/O elements]
  14: { name: 'iccid2', octeti: 8 }, // ICCID2 [Eventual I/O elements]
  15: { name: 'eco_score', mult: 0.01, octeti: 2 }, // Eco Score [Permanent I/O elements]
  17: { name: 'axis_x', semnat: true, octeti: 2, unit: "mG" }, // Axis X [Permanent I/O elements]
  18: { name: 'axis_y', semnat: true, octeti: 2, unit: "mG" }, // Axis Y [Permanent I/O elements]
  19: { name: 'axis_z', semnat: true, octeti: 2, unit: "mG" }, // Axis Z [Permanent I/O elements]
  20: { name: 'ble_battery_2', octeti: 1, unit: "%" }, // BLE Battery #2 [Bluetooth Low Energy]
  22: { name: 'ble_battery_3', octeti: 1, unit: "%" }, // BLE Battery #3 [Bluetooth Low Energy]
  23: { name: 'ble_battery_4', octeti: 1, unit: "%" }, // BLE Battery #4 [Bluetooth Low Energy]
  25: { name: 'ble_temperature_1', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // BLE Temperature #1 [Bluetooth Low Energy]
  26: { name: 'ble_temperature_2', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // BLE Temperature #2 [Bluetooth Low Energy]
  27: { name: 'ble_temperature_3', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // BLE Temperature #3 [Bluetooth Low Energy]
  28: { name: 'ble_temperature_4', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // BLE Temperature #4 [Bluetooth Low Energy]
  29: { name: 'ble_battery_1', octeti: 1, unit: "%" }, // BLE Battery #1 [Bluetooth Low Energy]
  30: { name: 'obd_dtc_count', octeti: 1 }, // Number of DTC [OBD elements]
  31: { name: 'obd_engine_load', octeti: 1, unit: "%" }, // Engine Load [OBD elements]
  32: { name: 'obd_coolant_temp', semnat: true, octeti: 1, unit: "°C" }, // Coolant Temperature [OBD elements]
  33: { name: 'obd_short_fuel_trim', semnat: true, octeti: 1, unit: "%" }, // Short Fuel Trim [OBD elements]
  37: { name: 'obd_vehicle_speed', octeti: 1, unit: "km/h" }, // Vehicle Speed [OBD elements]
  38: { name: 'obd_timing_advance', semnat: true, octeti: 1, unit: "°" }, // Timing Advance [OBD elements]
  39: { name: 'obd_intake_air_temperature', semnat: true, octeti: 1, unit: "°C" }, // Intake Air Temperature [OBD elements]
  40: { name: 'obd_maf', mult: 0.01, octeti: 2, unit: "g/sec" }, // MAF [OBD elements]
  41: { name: 'obd_throttle_position', octeti: 1, unit: "%" }, // Throttle Position [OBD elements]
  42: { name: 'obd_runtime_since_engine_start', octeti: 2, unit: "s" }, // Runtime since engine start [OBD elements]
  43: { name: 'obd_distance_traveled_mil_on', octeti: 2, unit: "km" }, // Distance Traveled MIL On [OBD elements]
  44: { name: 'obd_relative_fuel_rail_pressure', mult: 0.1, octeti: 2, unit: "kPa" }, // Relative Fuel Rail Pressure [OBD elements]
  45: { name: 'obd_direct_fuel_rail_pressure', mult: 10, octeti: 2, unit: "kPa" }, // Direct Fuel Rail Pressure [OBD elements]
  46: { name: 'obd_commanded_egr', octeti: 1, unit: "%" }, // Commanded EGR [OBD elements]
  47: { name: 'obd_egr_error', semnat: true, octeti: 1, unit: "%" }, // EGR Error [OBD elements]
  48: { name: 'obd_fuel_level', octeti: 1, unit: "%" }, // Fuel Level [OBD elements]
  49: { name: 'obd_distance_since_codes_clear', octeti: 2, unit: "km" }, // Distance Since Codes Clear [OBD elements]
  50: { name: 'obd_barometic_pressure', octeti: 1, unit: "kPa" }, // Barometic Pressure [OBD elements]
  51: { name: 'obd_control_module_voltage', mult: 0.001, octeti: 2, unit: "V" }, // Control Module Voltage [OBD elements]
  52: { name: 'obd_absolute_load_value', octeti: 2, unit: "%" }, // Absolute Load Value [OBD elements]
  53: { name: 'obd_ambient_air_temperature', semnat: true, octeti: 1, unit: "°C" }, // Ambient Air Temperature [OBD elements]
  54: { name: 'obd_time_run_with_mil_on', octeti: 2, unit: "min" }, // Time Run With MIL On [OBD elements]
  55: { name: 'obd_time_since_codes_cleared', octeti: 2, unit: "min" }, // Time Since Codes Cleared [OBD elements]
  56: { name: 'obd_absolute_fuel_rail_pressure', mult: 10, octeti: 2, unit: "kPa" }, // Absolute Fuel Rail Pressure [OBD elements]
  57: { name: 'obd_hybrid_battery_pack_life', octeti: 1, unit: "%" }, // Hybrid battery pack life [OBD elements]
  58: { name: 'obd_engine_oil_temperature', octeti: 1, unit: "°C" }, // Engine Oil Temperature [OBD elements]
  59: { name: 'obd_fuel_injection_timing', mult: 0.01, semnat: true, octeti: 2, unit: "°" }, // Fuel injection timing [OBD elements]
  60: { name: 'obd_fuel_rate', mult: 0.01, octeti: 2, unit: "L/h" }, // Fuel Rate [OBD elements]
  61: { name: 'geofence_zone_06', octeti: 1 }, // Geofence zone 06 [Eventual I/O elements]
  62: { name: 'geofence_zone_07', octeti: 1 }, // Geofence zone 07 [Eventual I/O elements]
  63: { name: 'geofence_zone_08', octeti: 1 }, // Geofence zone 08 [Eventual I/O elements]
  64: { name: 'geofence_zone_09', octeti: 1 }, // Geofence zone 09 [Eventual I/O elements]
  65: { name: 'geofence_zone_10', octeti: 1 }, // Geofence zone 10 [Eventual I/O elements]
  70: { name: 'geofence_zone_11', octeti: 1 }, // Geofence zone 11 [Eventual I/O elements]
  71: { name: 'dallas_temp_id_4', octeti: 8 }, // Dallas Temperature ID 4 [Permanent I/O elements]
  72: { name: 'dallas_temp_1', mult: 0.1, semnat: true, octeti: 4, unit: "°C" }, // Dallas Temperature 1 [Permanent I/O elements]
  73: { name: 'dallas_temp_2', mult: 0.1, semnat: true, octeti: 4, unit: "°C" }, // Dallas Temperature 2 [Permanent I/O elements]
  74: { name: 'dallas_temp_3', mult: 0.1, semnat: true, octeti: 4, unit: "°C" }, // Dallas Temperature 3 [Permanent I/O elements]
  75: { name: 'dallas_temp_4', mult: 0.1, semnat: true, octeti: 4, unit: "°C" }, // Dallas Temperature 4 [Permanent I/O elements]
  76: { name: 'dallas_temp_id_1', octeti: 8 }, // Dallas Temperature ID 1 [Permanent I/O elements]
  77: { name: 'dallas_temp_id_2', octeti: 8 }, // Dallas Temperature ID 2 [Permanent I/O elements]
  78: { name: 'ibutton', octeti: 8 }, // iButton [Permanent I/O elements]
  79: { name: 'dallas_temp_id_3', octeti: 8 }, // Dallas Temperature ID 3 [Permanent I/O elements]
  86: { name: 'ble_humidity_1', mult: 0.1, octeti: 2, unit: "%RH" }, // BLE Humidity #1 [Bluetooth Low Energy]
  99: { name: 'geofence_zone_21', octeti: 1 }, // Geofence zone 21 [Eventual I/O elements]
  104: { name: 'ble_humidity_2', mult: 0.1, octeti: 2, unit: "%RH" }, // BLE Humidity #2 [Bluetooth Low Energy]
  106: { name: 'ble_humidity_3', mult: 0.1, octeti: 2, unit: "%RH" }, // BLE Humidity #3 [Bluetooth Low Energy]
  108: { name: 'ble_humidity_4', mult: 0.1, octeti: 2, unit: "%RH" }, // BLE Humidity #4 [Bluetooth Low Energy]
  125: { name: 'can_harvesting_time', octeti: 4, unit: "min" }, // Harvesting Time [ALLCAN300]
  126: { name: 'can_area_of_harvest', octeti: 4, unit: "m 2" }, // Area of Harvest [ALLCAN300]
  127: { name: 'can_mowing_efficiency', octeti: 4, unit: "m 2 /h" }, // Mowing Efficiency [ALLCAN300]
  128: { name: 'can_grain_mown_volume', octeti: 4, unit: "kg" }, // Grain Mown Volume [ALLCAN300]
  129: { name: 'can_grain_moisture', octeti: 2, unit: "%" }, // Grain Moisture [ALLCAN300]
  130: { name: 'can_harvesting_drum_rpm', octeti: 2, unit: "rpm" }, // Harvesting Drum RPM [ALLCAN300]
  131: { name: 'can_gap_under_harvesting_drum', octeti: 1, unit: "mm" }, // Gap Under Harvesting Drum [ALLCAN300]
  136: { name: 'can_tacho_driver_card_presence', octeti: 1 }, // Tacho Driver Card Presence [ALLCAN300]
  137: { name: 'can_driver_1_states', octeti: 1 }, // Driver 1 States [ALLCAN300]
  138: { name: 'can_driver_2_states', octeti: 1 }, // Driver 2 States [ALLCAN300]
  139: { name: 'can_driver_1_continuous_driving_time', octeti: 2, unit: "min." }, // Driver 1 Continuous Driving Time [ALLCAN300]
  140: { name: 'can_driver_2_continuous_driving_time', octeti: 2, unit: "min." }, // Driver 2 Continuous Driving Time [ALLCAN300]
  141: { name: 'can_driver_1_cumulative_break_time', octeti: 2, unit: "min." }, // Driver 1 Cumulative Break Time [ALLCAN300]
  142: { name: 'can_driver_2_cumulative_break_time', octeti: 2, unit: "min." }, // Driver 2 Cumulative Break Time [ALLCAN300]
  143: { name: 'can_driver_1_selected_activity_duration', octeti: 2, unit: "min." }, // Driver 1 Selected Activity Duration [ALLCAN300]
  144: { name: 'can_driver_2_selected_activity_duration', octeti: 2, unit: "min." }, // Driver 2 Selected Activity Duration [ALLCAN300]
  145: { name: 'can_driver_1_cumulative_driving_time', octeti: 2, unit: "min." }, // Driver 1 Cumulative Driving Time [ALLCAN300]
  146: { name: 'can_driver_2_cumulative_driving_time', octeti: 2, unit: "min." }, // Driver 2 Cumulative Driving Time [ALLCAN300]
  147: { name: 'can_driver_1_id_high', octeti: 8 }, // Driver 1 ID High [ALLCAN300]
  148: { name: 'can_driver_1_id_low', octeti: 8 }, // Driver 1 ID Low [ALLCAN300]
  149: { name: 'can_driver_2_id_high', octeti: 8 }, // Driver 2 ID High [ALLCAN300]
  150: { name: 'can_driver_2_id_low', octeti: 8 }, // Driver 2 ID Low [ALLCAN300]
  153: { name: 'geofence_zone_22', octeti: 1 }, // Geofence zone 22 [Eventual I/O elements]
  154: { name: 'geofence_zone_23', octeti: 1 }, // Geofence zone 23 [Eventual I/O elements]
  155: { name: 'geofence_zone_01', octeti: 1 }, // Geofence zone 01 [Eventual I/O elements]
  156: { name: 'geofence_zone_02', octeti: 1 }, // Geofence zone 02 [Eventual I/O elements]
  157: { name: 'geofence_zone_03', octeti: 1 }, // Geofence zone 03 [Eventual I/O elements]
  158: { name: 'geofence_zone_04', octeti: 1 }, // Geofence zone 04 [Eventual I/O elements]
  159: { name: 'geofence_zone_05', octeti: 1 }, // Geofence zone 05 [Eventual I/O elements]
  161: { name: 'can_slope_of_arm', semnat: true, octeti: 2, unit: "Degrees °" }, // Slope of Arm [ALLCAN300]
  162: { name: 'can_rotation_of_arm', semnat: true, octeti: 2, unit: "Degrees °" }, // Rotation of Arm [ALLCAN300]
  163: { name: 'can_eject_of_arm', octeti: 2, unit: "m" }, // Eject of Arm [ALLCAN300]
  164: { name: 'can_horizontal_distance_arm_vehicle', octeti: 2, unit: "m" }, // Horizontal Distance Arm Vehicle [ALLCAN300]
  165: { name: 'can_height_arm_above_ground', octeti: 2, unit: "m" }, // Height Arm Above Ground [ALLCAN300]
  166: { name: 'can_drill_rpm', octeti: 2, unit: "rpm" }, // Drill RPM [ALLCAN300]
  167: { name: 'can_amount_of_spread_salt_square_meter', octeti: 2, unit: "g/m 2" }, // Amount Of Spread Salt Square Meter [ALLCAN300]
  168: { name: 'can_battery_voltage', octeti: 2, unit: "V" }, // Battery Voltage [ALLCAN300]
  169: { name: 'can_amount_of_spread_fine_grained_salt', octeti: 4, unit: "T" }, // Amount Of Spread Fine Grained Salt [ALLCAN300]
  170: { name: 'can_amount_of_coarse_grained_salt', octeti: 4, unit: "T" }, // Amount Of Coarse Grained Salt [ALLCAN300]
  171: { name: 'can_amount_of_spread_dimix', octeti: 4, unit: "T" }, // Amount Of Spread DiMix [ALLCAN300]
  172: { name: 'can_amount_of_spread_coarse_grained_calcium', octeti: 4, unit: "m 3" }, // Amount Of Spread Coarse Grained Calcium [ALLCAN300]
  173: { name: 'can_amount_of_spread_calcium_chloride', octeti: 4, unit: "m 3" }, // Amount Of Spread Calcium Chloride [ALLCAN300]
  174: { name: 'can_amount_of_spread_sodium_chloride', octeti: 4, unit: "m 3" }, // Amount Of Spread Sodium Chloride [ALLCAN300]
  176: { name: 'can_amount_of_spread_magnesium_chloride', octeti: 4, unit: "m 3" }, // Amount Of Spread Magnesium Chloride [ALLCAN300]
  177: { name: 'can_amount_of_spread_gravel', octeti: 4, unit: "T" }, // Amount Of Spread Gravel [ALLCAN300]
  178: { name: 'can_amount_of_spread_sand', octeti: 4, unit: "T" }, // Amount Of Spread Sand [ALLCAN300]
  183: { name: 'can_width_pouring_left', octeti: 2, unit: "m" }, // Width Pouring Left [ALLCAN300]
  184: { name: 'can_width_pouring_right', octeti: 2, unit: "m" }, // Width Pouring Right [ALLCAN300]
  185: { name: 'can_salt_spreader_working_hours', octeti: 4, unit: "h" }, // Salt Spreader Working Hours [ALLCAN300]
  186: { name: 'can_distance_during_salting', octeti: 4, unit: "km" }, // Distance During Salting [ALLCAN300]
  215: { name: 'lls_fuel_temp_5', semnat: true, octeti: 1, unit: "°C" }, // LLS 5 Temperature [Permanent I/O elements]
  216: { name: 'geofence_zone_35', octeti: 1 }, // Geofence zone 35 [Eventual I/O elements]
  217: { name: 'geofence_zone_36', octeti: 1 }, // Geofence zone 36 [Eventual I/O elements]
  224: { name: 'geofence_zone_43', octeti: 1 }, // Geofence zone 43 [Eventual I/O elements]
  225: { name: 'geofence_zone_44', octeti: 1 }, // Geofence zone 44 [Eventual I/O elements]
  226: { name: 'geofence_zone_45', octeti: 1 }, // Geofence zone 45 [Eventual I/O elements]
  227: { name: 'geofence_zone_46', octeti: 1 }, // Geofence zone 46 [Eventual I/O elements]
  228: { name: 'geofence_zone_47', octeti: 1 }, // Geofence zone 47 [Eventual I/O elements]
  229: { name: 'geofence_zone_48', octeti: 1 }, // Geofence zone 48 [Eventual I/O elements]
  230: { name: 'geofence_zone_49', octeti: 1 }, // Geofence zone 49 [Eventual I/O elements]
  231: { name: 'geofence_zone_50', octeti: 1 }, // Geofence zone 50 [Eventual I/O elements]
  233: { name: 'can_cng_used', octeti: 4, unit: "kg" }, // CNG Used [LVCAN200, CANCONTROL]
  234: { name: 'can_cng_level', octeti: 1, unit: "%" }, // CNG Level [LVCAN200, CANCONTROL]
  236: { name: 'alarm_event', octeti: 1 }, // Alarm [Eventual I/O elements]
  237: { name: 'network_type', octeti: 1 }, // Network Type [Permanent I/O elements]
  238: { name: 'user_id', octeti: 8 }, // User ID [Permanent I/O elements]
  243: { name: 'green_driving_event_duration', octeti: 2, unit: "ms" }, // Green driving event duration [Eventual I/O elements]
  248: { name: 'immobilizer', octeti: 1 }, // Immobilizer [Eventual I/O elements]
  249: { name: 'jamming', octeti: 1 }, // Jamming [Eventual I/O elements]
  256: { name: 'obd_vin', octeti: 17, ascii: true }, // VIN [OBD elements]
  257: { name: 'crash_trace_data' }, // Crash trace data [Eventual I/O elements]
  258: { name: 'ecomaximum', octeti: 8 }, // EcoMaximum [Eventual I/O elements]
  259: { name: 'ecoaverage', octeti: 8 }, // EcoAverage [Eventual I/O elements]
  260: { name: 'ecoduration', octeti: 2, unit: "ms" }, // EcoDuration [Eventual I/O elements]
  263: { name: 'bt_status', octeti: 1 }, // BT Status [Permanent I/O elements]
  264: { name: 'barcode_id', ascii: true }, // Barcode ID [FMBXXX FMB001 FMB010 FMB110 FMB120 FMB12]
  281: { name: 'obd_fault_codes', ascii: true }, // Fault Codes [OBD elements]
  303: { name: 'instant_movement', octeti: 1 }, // Instant Movement [Permanent I/O elements]
  304: { name: 'can_vehicles_range_on_battery', octeti: 4, unit: "m" }, // Vehicles Range On Battery [ALLCAN300, CANCONTROL]
  305: { name: 'can_vehicles_range_on_additional_fuel', octeti: 4, unit: "m" }, // Vehicles Range On Additional Fuel [ALLCAN300, CANCONTROL]
  306: { name: 'ble_fuel_frequency_1_306', octeti: 4 }, // BLE Fuel Frequency #1 [Bluetooth Low Energy]
  307: { name: 'ble_fuel_frequency_2_307', octeti: 4 }, // BLE Fuel Frequency #2 [Bluetooth Low Energy]
  308: { name: 'ble_fuel_frequency_3_308', octeti: 4 }, // BLE Fuel Frequency #3 [Bluetooth Low Energy]
  309: { name: 'ble_fuel_frequency_4_309', octeti: 4 }, // BLE Fuel Frequency #4 [Bluetooth Low Energy]
  317: { name: 'crash_event_counter', octeti: 1 }, // Crash event counter [Eventual I/O elements]
  318: { name: 'gnss_jamming', octeti: 1 }, // GNSS Jamming [Eventual I/O elements]
  325: { name: 'can_vin', octeti: 17, ascii: true }, // VIN [ALLCAN300, CANCONTROL]
  327: { name: 'ul202_fuel_level', mult: 0.1, semnat: true, octeti: 2, unit: "mm" }, // UL202-02 Sensor Fuel level [Permanent I/O elements]
  329: { name: 'ain_speed', octeti: 2 }, // AIN Speed [Permanent I/O elements]
  331: { name: 'ble_1_custom_1' }, // BLE 1 Custom #1 [Bluetooth Low Energy]
  332: { name: 'ble_2_custom_1' }, // BLE 2 Custom #1 [Bluetooth Low Energy]
  333: { name: 'ble_3_custom_1' }, // BLE 3 Custom #1 [Bluetooth Low Energy]
  334: { name: 'ble_4_custom_1' }, // BLE 4 Custom #1 [Bluetooth Low Energy]
  335: { name: 'ble_luminosity_1', octeti: 2, unit: "lx" }, // BLE Luminosity #1 [Bluetooth Low Energy]
  336: { name: 'ble_luminosity_2', octeti: 2, unit: "lx" }, // BLE Luminosity #2 [Bluetooth Low Energy]
  337: { name: 'ble_luminosity_3', octeti: 2, unit: "lx" }, // BLE Luminosity #3 [Bluetooth Low Energy]
  338: { name: 'ble_luminosity_4', octeti: 2, unit: "lx" }, // BLE Luminosity #4 [Bluetooth Low Energy]
  380: { name: 'digital_output_3', octeti: 1 }, // Digital output 3 [Permanent I/O elements]
  381: { name: 'ground_sense', octeti: 1 }, // Ground Sense [Permanent I/O elements]
  383: { name: 'axl_calibration_status', octeti: 1 }, // AXL Calibration Status [Permanent I/O elements]
  385: { name: 'beacon' }, // Beacon [Permanent I/O elements]
  388: { name: 'can_module_id_17b', octeti: 17 }, // Module ID 17B [LVCAN200, ALLCAN300, CANCONTROL]
  389: { name: 'obd_oem_total_mileage', octeti: 4, unit: "km" }, // OBD OEM Total Mileage [OBD OEM elements]
  390: { name: 'obd_oem_fuel_level', mult: 0.1, octeti: 4, unit: "l" }, // OBD OEM Fuel Level [OBD OEM elements]
  391: { name: 'private_mode', octeti: 1 }, // Private mode [Eventual I/O elements]
  400: { name: 'can_distance_to_next_service', octeti: 4 }, // Distance to Next Service [CAN adapters]
  402: { name: 'obd_oem_oem_distance_until_service', octeti: 4, unit: "km" }, // OEM Distance Until Service [OBD OEM elements]
  403: { name: 'driver_name', octeti: 35 }, // Driver Name [Permanent I/O elements]
  404: { name: 'driver_license_type', octeti: 1 }, // Driver card license type [Permanent I/O elements]
  405: { name: 'driver_gender', octeti: 1 }, // Driver Gender [Permanent I/O elements]
  406: { name: 'driver_card_id', octeti: 4 }, // Driver Card ID [Permanent I/O elements]
  407: { name: 'driver_card_expiry', octeti: 1 }, // Driver card expiration date [Permanent I/O elements]
  408: { name: 'driver_card_issue_place', octeti: 4 }, // Driver Card place of issue [Permanent I/O Elements]
  409: { name: 'driver_status_event', octeti: 1 }, // Driver Status Event [Permanent I/O elements]
  411: { name: 'obd_oem_oem_battery_charge_level', octeti: 1, unit: "%" }, // OEM Battery charge level [OBD OEM elements]
  449: { name: 'ignition_on_counter', octeti: 4, unit: "s" }, // Ignition On Counter [Eventual I/O elements]
  450: { name: 'can_cng_level_kg', mult: 10, octeti: 2, unit: "Kg" }, // CNG Level Kg [CAN adapters]
  451: { name: 'ble_rfid_1', octeti: 8 }, // BLE RFID #1 [Permanent I/O elements]
  452: { name: 'ble_rfid_2', octeti: 8 }, // BLE RFID #2 [Permanent I/O elements]
  453: { name: 'ble_rfid_3', octeti: 8 }, // BLE RFID #3 [Permanent I/O elements]
  454: { name: 'ble_rfid_4', octeti: 8 }, // BLE RFID #4 [Permanent I/O elements]
  455: { name: 'ble_button_1_state_1', octeti: 1 }, // BLE Button 1 state #1 [Permanent I/O elements]
  456: { name: 'ble_button_1_state_2', octeti: 1 }, // BLE Button 1 state #2 [Permanent I/O elements]
  457: { name: 'ble_button_1_state_3', octeti: 1 }, // BLE Button 1 state #3 [Permanent I/O elements]
  458: { name: 'ble_button_1_state_4', octeti: 1 }, // BLE Button 1 state #4 [Permanent I/O elements]
  459: { name: 'ble_button_2_state_1', octeti: 1 }, // BLE Button 2 state #1 [Permanent I/O elements]
  460: { name: 'ble_button_2_state_2', octeti: 1 }, // BLE Button 2 state #2 [Permanent I/O elements]
  461: { name: 'ble_button_2_state_3', octeti: 1 }, // BLE Button 2 state #3 [Permanent I/O elements]
  462: { name: 'ble_button_2_state_4', octeti: 1 }, // BLE Button 2 state #4 [Permanent I/O elements]
  463: { name: 'ble_1_custom_2', octeti: 4 }, // BLE 1 Custom #2 [Bluetooth Low Energy]
  464: { name: 'ble_1_custom_3', octeti: 4 }, // BLE 1 Custom #3 [Bluetooth Low Energy]
  465: { name: 'ble_1_custom_4', octeti: 4 }, // BLE 1 Custom #4 [Bluetooth Low Energy]
  466: { name: 'ble_1_custom_5', octeti: 4 }, // BLE 1 Custom #5 [Bluetooth Low Energy]
  467: { name: 'ble_2_custom_2', octeti: 4 }, // BLE 2 Custom #2 [Bluetooth Low Energy]
  468: { name: 'ble_2_custom_3', octeti: 4 }, // BLE 2 Custom #3 [Bluetooth Low Energy]
  469: { name: 'ble_2_custom_4', octeti: 4 }, // BLE 2 Custom #4 [Bluetooth Low Energy]
  470: { name: 'ble_2_custom_5', octeti: 4 }, // BLE 2 Custom #5 [Bluetooth Low Energy]
  471: { name: 'ble_3_custom_2', octeti: 4 }, // BLE 3 Custom #2 [Bluetooth Low Energy]
  472: { name: 'ble_3_custom_3', octeti: 4 }, // BLE 3 Custom #3 [Bluetooth Low Energy]
  473: { name: 'ble_3_custom_4', octeti: 4 }, // BLE 3 Custom #4 [Bluetooth Low Energy]
  474: { name: 'ble_3_custom_5', octeti: 4 }, // BLE 3 Custom #5 [Bluetooth Low Energy]
  475: { name: 'ble_4_custom_2', octeti: 4 }, // BLE 4 Custom #2 [Bluetooth Low Energy]
  476: { name: 'ble_4_custom_3', octeti: 4 }, // BLE 4 Custom #3 [Bluetooth Low Energy]
  477: { name: 'ble_4_custom_4', octeti: 4 }, // BLE 4 Custom #4 [Bluetooth Low Energy]
  478: { name: 'ble_4_custom_5', octeti: 4 }, // BLE 4 Custom #5 [Bluetooth Low Energy]
  483: { name: 'ul202_sensor_status', octeti: 1 }, // UL202-02 Sensor Status [Permanent I/O elements]
  500: { name: 'msp500_vendor_name', octeti: 40, ascii: true }, // MSP500 vendor name [Permanent I/O elements]
  501: { name: 'msp500_vehicle_number', octeti: 40, ascii: true }, // MSP500 vehicle number [Permanent I/O elements]
  502: { name: 'msp500_speed_sensor', octeti: 1 }, // MSP500 speed sensor [Permanent I/O elements]
  517: { name: 'can_security_state_flags_p4', octeti: 8 }, // Security State Flags P4 [ALLCAN300]
  518: { name: 'can_control_state_flags_p4', octeti: 8 }, // Control State Flags P4 [ALLCAN300]
  519: { name: 'can_indicator_state_flags_p4', octeti: 8 }, // Indicator State Flags P4 [ALLCAN300]
  520: { name: 'can_agricultural_state_flags_p4', octeti: 8 }, // Agricultural State Flags P4 [ALLCAN300]
  521: { name: 'can_utility_state_flags_p4', octeti: 8 }, // Utility State Flags P4 [ALLCAN300]
  522: { name: 'can_cistern_state_flags_p4', octeti: 8 }, // Cistern State Flags P4 [ALLCAN300]
  540: { name: 'obd_throttle_position_group', octeti: 1, unit: "%" }, // Throttle position group [OBD elements]
  541: { name: 'obd_commanded_equivalence_r', mult: 0.01, octeti: 1 }, // Commanded Equivalence R [OBD elements]
  542: { name: 'obd_intake_map_2_bytes', octeti: 2, unit: "kPa" }, // Intake MAP 2 bytes [OBD elements]
  543: { name: 'obd_hybrid_system_voltage', octeti: 2, unit: "V" }, // Hybrid System Voltage [OBD elements]
  544: { name: 'obd_hybrid_system_current', semnat: true, octeti: 2, unit: "A" }, // Hybrid System Current [OBD elements]
  548: { name: 'advanced_ble_beacon_data', octeti: 1024 }, // Advanced BLE Beacon data [Eventual I/O elements]
  622: { name: 'frequency_din1', mult: 0.1, octeti: 2, unit: "Hz" }, // Frequency DIN1 [Permanent I/O elements]
  623: { name: 'frequency_din2', mult: 0.1, octeti: 2, unit: "Hz" }, // Frequency DIN2 [Permanent I/O elements]
  636: { name: 'umts_lte_cell_id', octeti: 4 }, // UMTS/LTE Cell ID [Permanent I/O elements]
  637: { name: 'wake_reason', octeti: 1 }, // Wake Reason [Permanent I/O elements]
  652: { name: 'can_ssf_keyinignitionlock', octeti: 1 }, // SSF KeyInIgnitionLock [ALLCAN300, CANCONTROL]
  653: { name: 'can_ssf_handbrake_is_active', octeti: 1 }, // SSF Handbrake Is Active [ALLCAN300, CANCONTROL]
  654: { name: 'can_ssf_front_left_door_open', octeti: 1 }, // SSF Front Left Door Open [LVCAN, ALLCAN300, CANCONTROL]
  655: { name: 'can_ssf_front_right_door_open', octeti: 1 }, // SSF Front Right Door Open [LVCAN, ALLCAN300, CANCONTROL]
  656: { name: 'can_ssf_rear_left_door_open', octeti: 1 }, // SSF Rear Left Door Open [LVCAN, ALLCAN300, CANCONTROL]
  657: { name: 'can_ssf_rear_right_door_open', octeti: 1 }, // SSF Rear Right Door Open [LVCAN, ALLCAN300, CANCONTROL]
  658: { name: 'can_ssf_trunk_door_open', octeti: 1 }, // SSF Trunk Door Open [LVCAN, ALLCAN300, CANCONTROL]
  659: { name: 'can_ssf_neutral_gear_active_automatic_gear_box', octeti: 1 }, // SSF Neutral Gear Active (automatic gear box) [ALLCAN300, CANCONTROL]
  660: { name: 'can_ssf_parking_gear_active_automatic_gear_box', octeti: 1 }, // SSF Parking Gear Active (automatic gear box) [ALLCAN300, CANCONTROL]
  661: { name: 'can_ssf_reverse_gear_active', octeti: 1 }, // SSF Reverse Gear Active [ALLCAN300, CANCONTROL]
  662: { name: 'can_ssf_car_is_closed', octeti: 1 }, // SSF Car Is Closed [ALLCAN300, CANCONTROL]
  755: { name: 'obd_oem_oem_remaining_distance', octeti: 2, unit: "km" }, // OEM Remaining distance [OBD OEM elements]
  759: { name: 'obd_fuel_type', octeti: 1 }, // Fuel Type [OBD elements]
  855: { name: 'can_lng_used', octeti: 4, unit: "kg" }, // LNG Used [ALLCAN300, CANCONTROL]
  856: { name: 'can_lng_used_counted', octeti: 4, unit: "kg" }, // LNG Used (counted) [ALLCAN300, CANCONTROL]
  857: { name: 'can_lng_level', octeti: 2, unit: "%" }, // LNG Level [ALLCAN300, CANCONTROL]
  862: { name: 'can_time_from_need_of_service', octeti: 2, unit: "day" }, // Time from need of service [CAN adapters]
  863: { name: 'can_time_from_last_serivce', octeti: 2, unit: "day" }, // Time from last serivce [CAN adapters]
  864: { name: 'can_distance_to_next_oil_service', octeti: 4, unit: "km" }, // Distance to next oil service [CAN adapters]
  865: { name: 'can_time_to_next_oil_service', octeti: 2, unit: "day" }, // Time to next oil service [CAN adapters]
  866: { name: 'can_lvcan_vehicle_range', octeti: 4, unit: "km" }, // LVCAN Vehicle Range [CAN adapters]
  867: { name: 'can_lvcan_total_cng_counted', octeti: 4, unit: "kg" }, // LVCAN Total CNG counted [CAN adapters]
  898: { name: 'can_ssf_ignition', octeti: 1 }, // SSF Ignition [LVCAN, ALLCAN300, CANCONTROL]
  899: { name: 'can_ssf_webasto', octeti: 1 }, // SSF Webasto [ALLCAN300]
  900: { name: 'can_ssf_engine_working', octeti: 1 }, // SSF Engine Working [ALLCAN300, CANCONTROL]
  901: { name: 'can_ssf_standalone_engine', octeti: 1 }, // SSF Standalone Engine [ALLCAN300]
  902: { name: 'can_ssf_ready_to_drive', octeti: 1 }, // SSF Ready To Drive [ALLCAN300, CANCONTROL]
  903: { name: 'can_ssf_engine_working_on_cng', octeti: 1 }, // SSF Engine Working On CNG [ALLCAN300, CANCONTROL]
  904: { name: 'can_ssf_work_mode', octeti: 1 }, // SSF Work Mode [ALLCAN300]
  905: { name: 'can_ssf_operator', octeti: 1 }, // SSF Operator [ALLCAN300]
  906: { name: 'can_ssf_interlock', octeti: 1 }, // SSF Interlock [ALLCAN300]
  907: { name: 'can_ssf_engine_lock_active', octeti: 1 }, // SSF Engine Lock Active [CANCONTROL]
  908: { name: 'can_ssf_request_to_lock_engine', octeti: 1 }, // SSF Request To Lock Engine [CANCONTROL]
  909: { name: 'can_ssf_roof_open', octeti: 1 }, // SSF Roof Open [LVCAN, ALLCAN300, CANCONTROL]
  910: { name: 'can_ssf_footbrake_is_active', octeti: 1 }, // SSF Footbrake Is Active [ALLCAN300, CANCONTROL]
  911: { name: 'can_ssf_clutch_pushed', octeti: 1 }, // SSF Clutch Pushed [ALLCAN300, CANCONTROL]
  912: { name: 'can_ssf_hazard_warning_lights', octeti: 1 }, // SSF Hazard Warning Lights [ALLCAN300, CANCONTROL]
  913: { name: 'can_ssf_engine_cover_open', octeti: 1 }, // SSF Engine Cover Open [LVCAN, ALLCAN300, CANCONTROL]
  914: { name: 'can_ssf_charging_wire_plugged', octeti: 1 }, // SSF Charging Wire Plugged [ALLCAN300, CANCONTROL]
  915: { name: 'can_ssf_batttery_charging', octeti: 1 }, // SSF Batttery Charging [ALLCAN300, CANCONTROL]
  916: { name: 'can_ssf_electric_engine_state', octeti: 1 }, // SSF Electric Engine State [ALLCAN300, CANCONTROL]
  917: { name: 'can_ssf_car_closed_factory_remote', octeti: 1 }, // SSF Car Closed Factory Remote [ALLCAN300, CANCONTROL]
  918: { name: 'can_ssf_factory_alarm_actuated', octeti: 1 }, // SSF Factory Alarm Actuated [ALLCAN300, CANCONTROL]
  919: { name: 'can_ssf_factory_alarm_emulated', octeti: 1 }, // SSF Factory Alarm Emulated [ALLCAN300, CANCONTROL]
  920: { name: 'can_ssf_signal_close_factory_remote', octeti: 1 }, // SSF Signal Close Factory Remote [ALLCAN300, CANCONTROL]
  921: { name: 'can_ssf_signal_open_factory_remote', octeti: 1 }, // SSF Signal Open Factory Remote [ALLCAN300, CANCONTROL]
  922: { name: 'can_ssf_rearming_signal', octeti: 1 }, // SSF Rearming Signal [ALLCAN300, CANCONTROL]
  923: { name: 'can_ssf_trunk_door_opened_factory_remote', octeti: 1 }, // SSF Trunk Door Opened Factory Remote [ALLCAN300, CANCONTROL]
  924: { name: 'can_ssf_can_module_in_sleep', octeti: 1 }, // SSF CAN Module In Sleep [LVCAN, ALLCAN300, CANCONTROL]
  925: { name: 'can_ssf_factory_remote_3x', octeti: 1 }, // SSF Factory Remote 3x [ALLCAN300]
  926: { name: 'can_ssf_factory_armed', octeti: 1 }, // SSF Factory Armed [CANCONTROL]
  927: { name: 'can_ssf_drive_is_active_automatic_gear_box', octeti: 1 }, // SSF Drive Is Active (automatic gear box) [ALLCAN300, CANCONTROL]
  928: { name: 'can_csf_parking_lights', octeti: 1 }, // CSF Parking Lights [ALLCAN300, CANCONTROL]
  929: { name: 'can_csf_dipped_head_lights', octeti: 1 }, // CSF Dipped Head lights [ALLCAN300, CANCONTROL]
  930: { name: 'can_csf_full_beam_headlights', octeti: 1 }, // CSF Full Beam Headlights [ALLCAN300, CANCONTROL]
  931: { name: 'can_csf_rear_fog_lights', octeti: 1 }, // CSF Rear Fog Lights [ALLCAN300, CANCONTROL]
  932: { name: 'can_csf_front_fog_lights', octeti: 1 }, // CSF Front Fog Lights [ALLCAN300, CANCONTROL]
  933: { name: 'can_csf_additional_front_lights', octeti: 1 }, // CSF Additional Front Lights [ALLCAN300]
  934: { name: 'can_csf_additional_rear_lights', octeti: 1 }, // CSF Additional Rear Lights [ALLCAN300]
  935: { name: 'can_csf_light_signal', octeti: 1 }, // CSF Light Signal [ALLCAN300]
  936: { name: 'can_csf_air_conditioning', octeti: 1 }, // CSF Air Conditioning [ALLCAN300]
  937: { name: 'can_csf_cruise_control', octeti: 1 }, // CSF Cruise Control [ALLCAN300]
  938: { name: 'can_csf_automatic_retarder', octeti: 1 }, // CSF Automatic Retarder [ALLCAN300]
  939: { name: 'can_csf_manual_retarder', octeti: 1 }, // CSF Manual Retarder [ALLCAN300]
  940: { name: 'can_csf_driver_s_seatbelt_fastened', octeti: 1 }, // CSF Driver's Seatbelt Fastened [ALLCAN300]
  941: { name: 'can_csf_front_driver_s_seatbelt_fastened', octeti: 1 }, // CSF Front Driver's Seatbelt Fastened [ALLCAN300]
  942: { name: 'can_csf_left_driver_s_seatbelt_fastened', octeti: 1 }, // CSF Left Driver's Seatbelt Fastened [ALLCAN300]
  943: { name: 'can_csf_right_driver_s_seatbelt_fastened', octeti: 1 }, // CSF Right Driver's Seatbelt Fastened [ALLCAN300]
  944: { name: 'can_csf_centre_driver_s_seatbelt_fastened', octeti: 1 }, // CSF Centre Driver's Seatbelt Fastened [ALLCAN300]
  945: { name: 'can_csf_front_passenger_present', octeti: 1 }, // CSF Front Passenger Present [ALLCAN300]
  947: { name: 'can_csf_front_differential_locked', octeti: 1 }, // CSF Front Differential Locked [ALLCAN300]
  948: { name: 'can_csf_rear_differential_locked', octeti: 1 }, // CSF Rear Differential Locked [ALLCAN300]
  949: { name: 'can_csf_central_differential_4hi_locked', octeti: 1 }, // CSF Central Differential 4HI Locked [ALLCAN300]
  950: { name: 'can_csf_central_differential_4lo_locked', octeti: 1 }, // CSF Central Differential 4LO Locked [ALLCAN300]
  951: { name: 'can_csf_trailer_axle_1_lift_active', octeti: 1 }, // CSF Trailer Axle 1 Lift Active [ALLCAN300]
  952: { name: 'can_csf_trailer_axle_2_lift_active', octeti: 1 }, // CSF Trailer Axle 2 Lift Active [ALLCAN300]
  953: { name: 'can_isf_check_engine_indicator', octeti: 1 }, // ISF Check Engine Indicator [ALLCAN300]
  954: { name: 'can_isf_abs_indicator', octeti: 1 }, // ISF ABS Indicator [ALLCAN300]
  955: { name: 'can_isf_esp_indicator', octeti: 1 }, // ISF ESP Indicator [ALLCAN300]
  956: { name: 'can_isf_esp_turned_off', octeti: 1 }, // ISF ESP Turned Off [ALLCAN300]
  957: { name: 'can_isf_stop_indicator', octeti: 1 }, // ISF Stop Indicator [ALLCAN300]
  958: { name: 'can_isf_oil_level_indicator', octeti: 1 }, // ISF Oil Level Indicator [ALLCAN300, CANCONTROL]
  959: { name: 'can_isf_coolant_liquid_level', octeti: 1 }, // ISF Coolant liquid level [ALLCAN300]
  960: { name: 'can_isf_battery_not_charging_indicator', octeti: 1 }, // ISF Battery Not Charging Indicator [ALLCAN300]
  961: { name: 'can_isf_handbrake_system_indicator', octeti: 1 }, // ISF Handbrake System Indicator [ALLCAN300]
  962: { name: 'can_isf_airbag_indicator', octeti: 1 }, // ISF AIRBAG Indicator [ALLCAN300]
  963: { name: 'can_isf_eps_indicator', octeti: 1 }, // ISF EPS Indicator [ALLCAN300]
  964: { name: 'can_isf_warning_indicator', octeti: 1 }, // ISF Warning Indicator [ALLCAN300]
  965: { name: 'can_isf_lights_failure_indicator', octeti: 1 }, // ISF Lights Failure Indicator [ALLCAN300]
  966: { name: 'can_isf_low_tire_pressure_indicator', octeti: 1 }, // ISF Low Tire Pressure Indicator [ALLCAN300]
  967: { name: 'can_isf_wear_of_brake_pads_indicator', octeti: 1 }, // ISF Wear Of Brake Pads Indicator [ALLCAN300]
  968: { name: 'can_isf_low_fuel_level_indicator', octeti: 1 }, // ISF Low Fuel Level Indicator [ALLCAN300]
  969: { name: 'can_isf_maintenence_required_indicator', octeti: 1 }, // ISF Maintenence required Indicator [ALLCAN300]
  970: { name: 'can_isf_glow_plug_indicator', octeti: 1 }, // ISF Glow Plug Indicator [ALLCAN300]
  971: { name: 'can_isf_fap_indicator', octeti: 1 }, // ISF FAP Indicator [ALLCAN300]
  972: { name: 'can_isf_epc_electronic_power_control_indicator', octeti: 1 }, // ISF EPC (Electronic Power Control) Indicator [ALLCAN300]
  973: { name: 'can_isf_clogged_engine_oil_filter_indicator', octeti: 1 }, // ISF Clogged Engine Oil Filter Indicator [ALLCAN300]
  974: { name: 'can_isf_low_engine_oil_pressure_indicator', octeti: 1 }, // ISF Low Engine Oil Pressure Indicator [ALLCAN300]
  975: { name: 'can_isf_too_high_engine_oil_temperature_indicator', octeti: 1 }, // ISF Too High Engine Oil Temperature Indicator [ALLCAN300]
  976: { name: 'can_isf_low_coolant_level_indicator', octeti: 1 }, // ISF Low Coolant Level Indicator [ALLCAN300]
  977: { name: 'can_isf_clogged_hydraulic_system_oil_filter_indicator', octeti: 1 }, // ISF Clogged Hydraulic System Oil filter Indicator [ALLCAN300]
  978: { name: 'can_isf_hydraulic_system_low_pressure_indicator', octeti: 1 }, // ISF Hydraulic System Low Pressure Indicator [ALLCAN300]
  979: { name: 'can_isf_hydraulic_oil_low_level_indicator', octeti: 1 }, // ISF Hydraulic Oil Low Level Indicator [ALLCAN300]
  980: { name: 'can_isf_hydraulic_system_high_temperature_indicator', octeti: 1 }, // ISF Hydraulic System High Temperature Indicator [ALLCAN300]
  981: { name: 'can_isf_oil_overflow_in_hydraulic_chamber_indicator', octeti: 1 }, // ISF Oil Overflow In Hydraulic Chamber Indicator [ALLCAN300]
  982: { name: 'can_isf_clogged_air_filter_indicator', octeti: 1 }, // ISF Clogged Air Filter Indicator [ALLCAN300]
  983: { name: 'can_isf_clogged_fuel_filter_indicator', octeti: 1 }, // ISF Clogged Fuel Filter Indicator [ALLCAN300]
  984: { name: 'can_isf_water_in_fuel_indicator', octeti: 1 }, // ISF Water in Fuel Indicator [ALLCAN300]
  985: { name: 'can_isf_clogged_brake_system_filter_indicator', octeti: 1 }, // ISF Clogged Brake System Filter Indicator [ALLCAN300]
  986: { name: 'can_isf_low_washer_fluid_level_indicator', octeti: 1 }, // ISF Low Washer Fluid Level Indicator [LVCAN, ALLCAN300]
  987: { name: 'can_isf_low_adblue_level_indicator', octeti: 1 }, // ISF Low AdBlue Level Indicator [LVCAN, ALLCAN300]
  988: { name: 'can_isf_low_trailer_tyre_pressure_indicator', octeti: 1 }, // ISF Low Trailer Tyre Pressure Indicator [ALLCAN300]
  989: { name: 'can_isf_wear_of_trailer_brake_lining_indicator', octeti: 1 }, // ISF Wear Of Trailer Brake Lining Indicator [ALLCAN300]
  990: { name: 'can_isf_high_trailer_brake_temperature_indicator', octeti: 1 }, // ISF High Trailer Brake Temperature Indicator [ALLCAN300]
  991: { name: 'can_isf_incorrect_trailer_pneumatic_supply_indicator', octeti: 1 }, // ISF Incorrect Trailer Pneumatic Supply Indicator [ALLCAN300]
  992: { name: 'can_isf_low_cng_level_indicator', octeti: 1 }, // ISF Low CNG Level Indicator [LVCAN, ALLCAN300]
  993: { name: 'can_asf_right_joystick_moved_right_active', octeti: 1 }, // ASF Right Joystick Moved Right Active [ALLCAN300]
  994: { name: 'can_asf_right_joystick_moved_left_active', octeti: 1 }, // ASF Right Joystick Moved Left Active [ALLCAN300]
  995: { name: 'can_asf_right_joystick_moved_forward_active', octeti: 1 }, // ASF Right Joystick Moved Forward Active [ALLCAN300]
  996: { name: 'can_asf_right_joystick_moved_back_active', octeti: 1 }, // ASF Right Joystick Moved Back Active [ALLCAN300]
  997: { name: 'can_asf_left_joystick_moved_right_active', octeti: 1 }, // ASF Left Joystick Moved Right Active [ALLCAN300]
  998: { name: 'can_asf_left_joystick_moved_left_active', octeti: 1 }, // ASF Left Joystick Moved Left Active [ALLCAN300]
  999: { name: 'can_asf_left_joystick_moved_forward_active', octeti: 1 }, // ASF Left Joystick Moved Forward Active [ALLCAN300]
  1000: { name: 'can_asf_left_joystick_moved_back_active', octeti: 1 }, // ASF Left Joystick Moved Back Active [ALLCAN300]
  1001: { name: 'can_asf_first_rear_hydraulic', octeti: 1 }, // ASF First Rear hydraulic [ALLCAN300]
  1002: { name: 'can_asf_second_rear_hydraulic', octeti: 1 }, // ASF Second Rear hydraulic [ALLCAN300]
  1003: { name: 'can_asf_third_rear_hydraulic', octeti: 1 }, // ASF Third Rear hydraulic [ALLCAN300]
  1004: { name: 'can_asf_fourth_rear_hydraulic', octeti: 1 }, // ASF Fourth Rear hydraulic [ALLCAN300]
  1005: { name: 'can_asf_first_front_hydraulic', octeti: 1 }, // ASF First Front hydraulic [ALLCAN300]
  1006: { name: 'can_asf_second_front_hydraulic', octeti: 1 }, // ASF Second Front hydraulic [ALLCAN300]
  1007: { name: 'can_asf_third_front_hydraulic', octeti: 1 }, // ASF Third Front hydraulic [ALLCAN300]
  1008: { name: 'can_asf_fourth_front_hydraulic', octeti: 1 }, // ASF Fourth Front hydraulic [ALLCAN300]
  1009: { name: 'can_asf_front_three_point_hitch', octeti: 1 }, // ASF Front Three-point Hitch [ALLCAN300]
  1010: { name: 'can_asf_rear_three_point_hitch', octeti: 1 }, // ASF Rear Three-point Hitch [ALLCAN300]
  1011: { name: 'can_asf_front_power_take_off', octeti: 1 }, // ASF Front Power Take-off [ALLCAN300]
  1012: { name: 'can_asf_rear_power_take_off', octeti: 1 }, // ASF Rear Power Take-off [ALLCAN300]
  1013: { name: 'can_asf_mowing_active', octeti: 1 }, // ASF Mowing Active [ALLCAN300]
  1014: { name: 'can_asf_threshing_active', octeti: 1 }, // ASF Threshing Active [ALLCAN300]
  1015: { name: 'can_asf_grain_release_from_hopper', octeti: 1 }, // ASF Grain Release From Hopper [ALLCAN300]
  1016: { name: 'can_asf_grain_tank_is_100_full', octeti: 1 }, // ASF Grain Tank Is 100% Full [ALLCAN300]
  1017: { name: 'can_asf_grain_tank_is_70_full', octeti: 1 }, // ASF Grain Tank Is 70% Full [ALLCAN300]
  1018: { name: 'can_asf_grain_tank_is_opened', octeti: 1 }, // ASF Grain Tank Is Opened [ALLCAN300]
  1019: { name: 'can_asf_unloader_drive', octeti: 1 }, // ASF Unloader Drive [ALLCAN300]
  1020: { name: 'can_asf_cleaning_fan_control_turned_off', octeti: 1 }, // ASF Cleaning Fan Control Turned Off [ALLCAN300]
  1021: { name: 'can_asf_threshing_drum_control_turned_off', octeti: 1 }, // ASF Threshing Drum Control Turned Off [ALLCAN300]
  1022: { name: 'can_asf_straw_walker_is_clogged', octeti: 1 }, // ASF Straw Walker Is Clogged [ALLCAN300]
  1023: { name: 'can_asf_excessive_clearance_under_the_threshing_drum', octeti: 1 }, // ASF Excessive Clearance Under The Threshing Drum [ALLCAN300]
  1024: { name: 'can_asf_low_temperature_of_drive_system_hydraulics_less_than_5_grades', octeti: 1 }, // ASF Low Temperature Of Drive System Hydraulics Less Than 5 Grades [ALLCAN300]
  1025: { name: 'can_asf_high_temperature_of_drive_system_hydraulics_greater_than_86_grades', octeti: 1 }, // ASF High Temperature Of Drive System Hydraulics Greater Than 86 Grades [ALLCAN300]
  1026: { name: 'can_asf_ear_auger_speed_below_the_norm', octeti: 1 }, // ASF Ear Auger Speed Below The Norm [ALLCAN300]
  1027: { name: 'can_asf_grain_auger_speed_below_the_norm', octeti: 1 }, // ASF Grain Auger Speed Below The Norm [ALLCAN300]
  1028: { name: 'can_asf_straw_chooper_speed_below_the_norm', octeti: 1 }, // ASF Straw Chooper Speed Below The Norm [ALLCAN300]
  1029: { name: 'can_asf_straw_shaker_speed_below_the_norm', octeti: 1 }, // ASF Straw Shaker Speed Below The Norm [ALLCAN300]
  1030: { name: 'can_asf_feeder_speed_below_the_norm', octeti: 1 }, // ASF Feeder Speed Below The Norm [ALLCAN300]
  1031: { name: 'can_asf_straw_chopper_switched_on', octeti: 1 }, // ASF Straw Chopper Switched On [ALLCAN300]
  1032: { name: 'can_asf_corn_header_connected', octeti: 1 }, // ASF Corn Header Connected [ALLCAN300]
  1033: { name: 'can_asf_grain_header_connected', octeti: 1 }, // ASF Grain Header Connected [ALLCAN300]
  1034: { name: 'can_asf_feeder_reverse_switched_on', octeti: 1 }, // ASF Feeder Reverse Switched On [ALLCAN300]
  1035: { name: 'can_asf_the_pressure_filter_of_the_hydraulic_pump_is_clogged', octeti: 1 }, // ASF The Pressure Filter Of The Hydraulic Pump Is Clogged [ALLCAN300]
  1036: { name: 'can_usf_spreading', octeti: 1 }, // USF Spreading [ALLCAN300]
  1037: { name: 'can_usf_pouring_chemicals', octeti: 1 }, // USF Pouring Chemicals [ALLCAN300]
  1038: { name: 'can_usf_conveyor_belt', octeti: 1 }, // USF Conveyor Belt [ALLCAN300]
  1039: { name: 'can_usf_salt_spreader_s_drive_wheel', octeti: 1 }, // USF Salt Spreader's Drive Wheel [ALLCAN300]
  1040: { name: 'can_usf_brushes', octeti: 1 }, // USF Brushes [ALLCAN300]
  1041: { name: 'can_usf_vacuum_cleaner', octeti: 1 }, // USF Vacuum Cleaner [ALLCAN300]
  1042: { name: 'can_usf_water_supply', octeti: 1 }, // USF Water Supply [ALLCAN300]
  1043: { name: 'can_usf_karcheron', octeti: 1 }, // USF KarcherOn [ALLCAN300]
  1044: { name: 'can_usf_liquid_pump', octeti: 1 }, // USF Liquid pump [ALLCAN300]
  1045: { name: 'can_usf_unloading_from_the_hopper', octeti: 1 }, // USF Unloading From The Hopper [ALLCAN300]
  1046: { name: 'can_usf_low_salt_sand_level_in_container_indicator', octeti: 1 }, // USF Low Salt (Sand) Level In Container Indicator [ALLCAN300]
  1047: { name: 'can_usf_low_water_level_in_container_indicator', octeti: 1 }, // USF Low Water Level in Container Indicator [ALLCAN300]
  1048: { name: 'can_usf_chemicals', octeti: 1 }, // USF Chemicals [ALLCAN300]
  1049: { name: 'can_usf_compressor', octeti: 1 }, // USF Compressor [ALLCAN300]
  1050: { name: 'can_usf_water_valve_is_opened', octeti: 1 }, // USF Water Valve Is Opened [ALLCAN300]
  1051: { name: 'can_usf_cabin_moved_up_status_active', octeti: 1 }, // USF Cabin Moved Up Status Active [ALLCAN300]
  1052: { name: 'can_usf_cabin_moved_down_status_active', octeti: 1 }, // USF Cabin Moved Down Status Active [ALLCAN300]
  1053: { name: 'can_cisf_section_1_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 1 Presence Of Fluid In The Downpipe [ALLCAN300]
  1054: { name: 'can_cisf_section_1_filled', octeti: 1 }, // CiSF Section 1 Filled [ALLCAN300]
  1055: { name: 'can_cisf_section_1_overfilled', octeti: 1 }, // CiSF Section 1 Overfilled [ALLCAN300]
  1056: { name: 'can_cisf_section_2_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 2 Presence Of Fluid In The Downpipe [ALLCAN300]
  1057: { name: 'can_cisf_section_2_filled', octeti: 1 }, // CiSF Section 2 Filled [ALLCAN300]
  1058: { name: 'can_cisf_section_2_overfilled', octeti: 1 }, // CiSF Section 2 Overfilled [ALLCAN300]
  1059: { name: 'can_cisf_section_3_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 3 Presence Of Fluid In The Downpipe [ALLCAN300]
  1060: { name: 'can_cisf_section_3_filled', octeti: 1 }, // CiSF Section 3 Filled [ALLCAN300]
  1061: { name: 'can_cisf_section_3_overfilled', octeti: 1 }, // CiSF Section 3 Overfilled [ALLCAN300]
  1062: { name: 'can_cisf_section_4_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 4 Presence Of Fluid In The Downpipe [ALLCAN300]
  1063: { name: 'can_cisf_section_4_filled', octeti: 1 }, // CiSF Section 4 Filled [ALLCAN300]
  1064: { name: 'can_cisf_section_4_overfilled', octeti: 1 }, // CiSF Section 4 Overfilled [ALLCAN300]
  1065: { name: 'can_cisf_section_5_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 5 Presence Of Fluid In The Downpipe [ALLCAN300]
  1066: { name: 'can_cisf_section_5_filled', octeti: 1 }, // CiSF Section 5 Filled [ALLCAN300]
  1067: { name: 'can_cisf_section_5_overfilled', octeti: 1 }, // CiSF Section 5 Overfilled [ALLCAN300]
  1068: { name: 'can_cisf_section_6_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 6 Presence Of Fluid In The Downpipe [ALLCAN300]
  1069: { name: 'can_cisf_section_6_filled', octeti: 1 }, // CiSF Section 6 Filled [ALLCAN300]
  1070: { name: 'can_cisf_section_6_overfilled', octeti: 1 }, // CiSF Section 6 Overfilled [ALLCAN300]
  1071: { name: 'can_cisf_section_7_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 7 Presence Of Fluid In The Downpipe [ALLCAN300]
  1072: { name: 'can_cisf_section_7_filled', octeti: 1 }, // CiSF Section 7 Filled [ALLCAN300]
  1073: { name: 'can_cisf_section_7_overfilled', octeti: 1 }, // CiSF Section 7 Overfilled [ALLCAN300]
  1074: { name: 'can_cisf_section_8_presence_of_fluid_in_the_downpipe', octeti: 1 }, // CiSF Section 8 Presence Of Fluid In The Downpipe [ALLCAN300]
  1075: { name: 'can_cisf_section_8_filled', octeti: 1 }, // CiSF Section 8 Filled [ALLCAN300]
  1076: { name: 'can_cisf_section_8_overfilled', octeti: 1 }, // CiSF Section 8 Overfilled [ALLCAN300]
  1079: { name: 'can_total_bale_count', octeti: 4 }, // Total Bale Count [CAN adapters]
  1080: { name: 'can_bale_count', octeti: 4 }, // Bale Count [CAN adapters]
  1081: { name: 'can_cut_bale_count', octeti: 4 }, // Cut Bale Count [CAN adapters]
  1082: { name: 'can_bale_slices', octeti: 4 }, // Bale Slices [CAN adapters]
  1083: { name: 'can_ssf_engine_working_on_dual_fuel', octeti: 1 }, // SSF Engine Working On Dual Fuel [ALLCAN300]
  1084: { name: 'can_ssf_engine_working_on_lpg', octeti: 1 }, // SSF Engine Working On LPG [ALLCAN300]
  1085: { name: 'can_csf_trailer_connected', octeti: 1 }, // CSF Trailer Connected [ALLCAN300]
  1086: { name: 'can_csf_start_stop_system_inactive', octeti: 1 }, // CSF Start Stop System Inactive [ALLCAN300]
  1087: { name: 'can_asf_adapter_pressure_filter_sensor', octeti: 1 }, // ASF Adapter Pressure Filter Sensor [ALLCAN300]
  1088: { name: 'can_asf_service_2_required_indicator', octeti: 1 }, // ASF Service 2 Required Indicator [ALLCAN300]
  1089: { name: 'can_asf_drain_filter_clogged_indicator', octeti: 1 }, // ASF Drain Filter Clogged Indicator [ALLCAN300]
  1090: { name: 'can_asf_section_1_spraying', octeti: 1 }, // ASF Section 1 Spraying [ALLCAN300]
  1091: { name: 'can_asf_section_2_spraying', octeti: 1 }, // ASF Section 2 Spraying [ALLCAN300]
  1092: { name: 'can_asf_section_3_spraying', octeti: 1 }, // ASF Section 3 Spraying [ALLCAN300]
  1093: { name: 'can_asf_section_4_spraying', octeti: 1 }, // ASF Section 4 Spraying [ALLCAN300]
  1094: { name: 'can_asf_section_5_spraying', octeti: 1 }, // ASF Section 5 Spraying [ALLCAN300]
  1095: { name: 'can_asf_section_6_spraying', octeti: 1 }, // ASF Section 6 Spraying [ALLCAN300]
  1096: { name: 'can_asf_section_7_spraying', octeti: 1 }, // ASF Section 7 Spraying [ALLCAN300]
  1097: { name: 'can_asf_section_8_spraying', octeti: 1 }, // ASF Section 8 Spraying [ALLCAN300]
  1098: { name: 'can_asf_section_9_spraying', octeti: 1 }, // ASF Section 9 Spraying [ALLCAN300]
  1099: { name: 'can_usf_hydraulics_work_not_permitted', octeti: 1 }, // USF Hydraulics Work Not Permitted [ALLCAN300]
  1100: { name: 'can_total_lpg_used', octeti: 4, unit: "l" }, // Total LPG Used [LVCAN]
  1101: { name: 'can_total_lpg_used_counted', octeti: 4, unit: "l" }, // Total LPG Used Counted [LVCAN]
  1102: { name: 'can_lpg_level_proc', octeti: 2, unit: "%" }, // LPG Level Proc [LVCAN]
  1103: { name: 'can_lpg_level_liters', octeti: 2, unit: "l" }, // LPG Level Liters [LVCAN]
  1117: { name: 'can_lvcan_exceededroadspeed', octeti: 1, unit: "km/h" }, // LVCAN ExceededRoadSpeed [CAN adapters]
  1148: { name: 'connectivity_quality', octeti: 4 }, // Connectivity quality [Permanent I/O elements]
  1149: { name: 'current_lte_band', octeti: 1 }, // Current LTE Band [Permanent I/O elements]
  1151: { name: 'obd_oem_oem_battery_state_of_health', octeti: 2, unit: "%" }, // OEM Battery State Of Health [OBD OEM elements]
  1152: { name: 'obd_oem_oem_battery_temperature', semnat: true, octeti: 2, unit: "°C" }, // OEM Battery Temperature [OBD OEM elements]
  1205: { name: 'can_lvcan_rsf_speedlimitsign', octeti: 1 }, // LVCAN RSF SpeedLimitSign [CAN adapters]
  1206: { name: 'can_lvcan_rsf_endofspeedlimitsign', octeti: 1 }, // LVCAN RSF EndOfSpeedLimitSign [CAN adapters]
  1207: { name: 'can_lvcan_rsf_speedexceeded', octeti: 1 }, // LVCAN RSF SpeedExceeded [CAN adapters]
  1208: { name: 'can_lvcan_rsf_timespeedlimitsign', octeti: 1 }, // LVCAN RSF TimeSpeedLimitSign [CAN adapters]
  1209: { name: 'can_lvcan_rsf_wthrspeedlimitsign', octeti: 1 }, // LVCAN RSF WthrSpeedLimitSign [CAN adapters]
  1211: { name: 'can_ssf_front_left_window_open', octeti: 1 }, // SSF Front Left Window Open [LVCAN elements]
  1212: { name: 'can_ssf_front_right_window_open', octeti: 1 }, // SSF Front Right Window Open [LVCAN elements]
  1213: { name: 'can_ssf_rear_left_window_open', octeti: 1 }, // SSF Rear Left Window Open [LVCAN elements]
  1214: { name: 'can_ssf_rear_right_window_open', octeti: 1 }, // SSF Rear Right Window Open [LVCAN elements]
  1412: { name: 'motorcycle_fall_detection', octeti: 1 }, // Motorcycle Fall Detection [Eventual I/O elements]
  1593: { name: 'obd_calc_remaining_distance', octeti: 2, unit: "Km" }, // Calc Remaining Distance [OBD elements]
  10800: { name: 'eye_temperature_1', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // EYE Temperature 1 [Permanent I/O elements]
  10801: { name: 'eye_temperature_2', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // EYE Temperature 2 [Permanent I/O elements]
  10802: { name: 'eye_temperature_3', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // EYE Temperature 3 [Permanent I/O elements]
  10803: { name: 'eye_temperature_4', mult: 0.01, semnat: true, octeti: 2, unit: "°C" }, // EYE Temperature 4 [Permanent I/O elements]
  10804: { name: 'eye_humidity_1', octeti: 1, unit: "%" }, // EYE Humidity 1 [Permanent I/O elements]
  10805: { name: 'eye_humidity_2', octeti: 1, unit: "%" }, // EYE Humidity 2 [Permanent I/O elements]
  10806: { name: 'eye_humidity_3', octeti: 1, unit: "%" }, // EYE Humidity 3 [Permanent I/O elements]
  10807: { name: 'eye_humidity_4', octeti: 1, unit: "%" }, // EYE Humidity 4 [Permanent I/O elements]
  10808: { name: 'eye_magnet_1', octeti: 1 }, // EYE Magnet 1 [Permanent I/O elements]
  10809: { name: 'eye_magnet_2', octeti: 1 }, // EYE Magnet 2 [Permanent I/O elements]
  10810: { name: 'eye_magnet_3', octeti: 1 }, // EYE Magnet 3 [Permanent I/O elements]
  10811: { name: 'eye_magnet_4', octeti: 1 }, // EYE Magnet 4 [Permanent I/O elements]
  10812: { name: 'eye_movement_1', octeti: 1 }, // EYE Movement 1 [Permanent I/O elements]
  10813: { name: 'eye_movement_2', octeti: 1 }, // EYE Movement 2 [Permanent I/O elements]
  10814: { name: 'eye_movement_3', octeti: 1 }, // EYE Movement 3 [Permanent I/O elements]
  10815: { name: 'eye_movement_4', octeti: 1 }, // EYE Movement 4 [Permanent I/O elements]
  10816: { name: 'eye_pitch_1', semnat: true, octeti: 1 }, // EYE Pitch 1 [Permanent I/O elements]
  10817: { name: 'eye_pitch_2', semnat: true, octeti: 1 }, // EYE Pitch 2 [Permanent I/O elements]
  10818: { name: 'eye_pitch_3', semnat: true, octeti: 1 }, // EYE Pitch 3 [Permanent I/O elements]
  10819: { name: 'eye_pitch_4', semnat: true, octeti: 1 }, // EYE Pitch 4 [Permanent I/O elements]
  10820: { name: 'eye_low_battery_1', octeti: 1 }, // EYE Low Battery 1 [Permanent I/O elements]
  10821: { name: 'eye_low_battery_2', octeti: 1 }, // EYE Low Battery 2 [Permanent I/O elements]
  10822: { name: 'eye_low_battery_3', octeti: 1 }, // EYE Low Battery 3 [Permanent I/O elements]
  10823: { name: 'eye_low_battery_4', octeti: 1 }, // EYE Low Battery 4 [Permanent I/O elements]
  10824: { name: 'eye_battery_voltage_1', octeti: 2 }, // EYE Battery Voltage 1 [Permanent I/O elements]
  10825: { name: 'eye_battery_voltage_2', octeti: 2 }, // EYE Battery Voltage 2 [Permanent I/O elements]
  10826: { name: 'eye_battery_voltage_3', octeti: 2 }, // EYE Battery Voltage 3 [Permanent I/O elements]
  10827: { name: 'eye_battery_voltage_4', octeti: 2 }, // EYE Battery Voltage 4 [Permanent I/O elements]
  10832: { name: 'eye_roll_1', semnat: true, octeti: 2 }, // EYE Roll 1 [Permanent I/O elements]
  10833: { name: 'eye_roll_2', semnat: true, octeti: 2 }, // EYE Roll 2 [Permanent I/O elements]
  10834: { name: 'eye_roll_3', semnat: true, octeti: 2 }, // EYE Roll 3 [Permanent I/O elements]
  10835: { name: 'eye_roll_4', semnat: true, octeti: 2 }, // EYE Roll 4 [Permanent I/O elements]
  10836: { name: 'eye_movement_count_1', octeti: 2 }, // EYE Movement count 1 [Permanent I/O elements]
  10837: { name: 'eye_movement_count_2', octeti: 2 }, // EYE Movement count 2 [Permanent I/O elements]
  10838: { name: 'eye_movement_count_3', octeti: 2 }, // EYE Movement count 3 [Permanent I/O elements]
  10839: { name: 'eye_movement_count_4', octeti: 2 }, // EYE Movement count 4 [Permanent I/O elements]
  10840: { name: 'eye_magnet_count_1', octeti: 2 }, // EYE Magnet count 1 [Permanent I/O elements]
  10841: { name: 'eye_magnet_count_2', octeti: 2 }, // EYE Magnet count 2 [Permanent I/O elements]
  10842: { name: 'eye_magnet_count_3', octeti: 2 }, // EYE Magnet count 3 [Permanent I/O elements]
  10843: { name: 'eye_magnet_count_4', octeti: 2 }, // EYE Magnet count 4 [Permanent I/O elements]
  13201: { name: 'pcb_temperature', mult: 0.1, semnat: true, octeti: 2, unit: "°C" }, // PCB Temperature [Permanent I/O elements]
};
